from __future__ import annotations

from pathlib import Path

from backend.db import init_trading_core_v2_schema

REPO_ROOT = Path(__file__).resolve().parents[3]
TRADING_CORE_MIGRATION = REPO_ROOT / "backend" / "migrations" / "trading_core_v2_schema.sql"
ACCOUNT_SLOT_MIGRATION = REPO_ROOT / "backend" / "migrations" / "add_simulation_runtime_account_slots_20260604.sql"
LOCALSIM_SUCCESSOR_MIGRATION = REPO_ROOT / "backend" / "migrations" / "localsim_successor_core_20260831.sql"
LOCALSIM_CUTOVER_BRIDGE_MIGRATION = (
    REPO_ROOT / "backend" / "migrations" / "localsim_product_cutover_bridge_20260831.sql"
)


def test_runtime_release_and_binding_schema_are_commented_in_migration_and_bootstrap() -> None:
    expected = {
        "strategy_pkg.selection_score_artifact": [
            "artifact_id",
            "package_id",
            "manifest_sha256",
            "trade_date",
            "data_source",
            "runtime_config_hash",
            "scores_json",
            "artifact_sha256",
            "score_count",
            "universe_count",
            "top_score_symbol",
            "status",
            "error_json",
            "metadata",
            "artifact_contract_version",
            "artifact_payload_sha256",
            "artifact_input_context_hash",
            "source_revision_set_hash",
            "asset_closure_hash",
            "created_at",
        ],
        "strategy_pkg.strategy_runtime_release": [
            "release_id",
            "package_id",
            "manifest_sha256",
            "base_release_id",
            "runtime_profile_id",
            "runtime_profile_version_id",
            "runtime_profile_sha256",
            "daily_strategy_profile_version_id",
            "execution_policy_version_id",
            "execution_policy_sha256",
            "tail_policy_version_id",
            "tail_policy_sha256",
            "release_config_json",
            "release_hash",
            "validation_state",
            "validation_evidence",
            "effective_from",
            "effective_to",
            "created_by",
            "created_reason",
            "created_at",
            "updated_at",
        ],
        "paper_v2.simulation_release_binding": [
            "binding_id",
            "strategy_id",
            "release_id",
            "release_hash",
            "package_id",
            "manifest_sha256",
            "broker_backend",
            "broker_account_id",
            "account_group_id",
            "strategy_slot_id",
            "capital_allocation",
            "strategy_name",
            "order_remark_prefix",
            "effective_from",
            "effective_to",
            "approval_state",
            "binding_config_json",
            "binding_hash",
            "created_by",
            "created_reason",
            "created_at",
            "updated_at",
        ],
        "paper_v2.simulation_account_v1": [
            "account_id",
            "account_hash",
            "schema_version",
            "account_name",
            "broker_backend",
            "package_id",
            "manifest_sha256",
            "admission_receipt_id",
            "initial_capital",
            "account_config_json",
            "status",
            "version",
            "created_by",
            "created_at",
            "updated_at",
        ],
        "paper_v2.simulation_ledger_scope_v1": [
            "ledger_scope_id",
            "ledger_scope_hash",
            "schema_version",
            "scope_kind",
            "source_identity",
            "native_account_id",
            "created_by",
            "created_at",
        ],
        "paper_v2.localsim_runtime_profile_v1": [
            "profile_id",
            "profile_hash",
            "schema_version",
            "package_id",
            "manifest_sha256",
            "profile_name",
            "status",
            "version",
            "created_by",
            "created_at",
            "updated_at",
        ],
        "paper_v2.localsim_runtime_profile_version_v1": [
            "profile_version_id",
            "profile_version_hash",
            "schema_version",
            "profile_id",
            "package_id",
            "manifest_sha256",
            "version_no",
            "config_json",
            "config_sha256",
            "daily_strategy_profile_version_id",
            "validation_status",
            "validation_evidence",
            "created_by",
            "created_at",
        ],
        "paper_v2.legacy_localsim_account_lineage_v1": [
            "lineage_id",
            "lineage_hash",
            "schema_version",
            "legacy_account_id",
            "account_id",
            "release_id",
            "binding_id",
            "ledger_scope_id",
            "economic_facts_sha256",
            "status",
            "version",
            "created_by",
            "created_at",
            "updated_at",
        ],
        "paper_v2.localsim_replay_job_v1": [
            "replay_job_id",
            "replay_hash",
            "schema_version",
            "simulation_account_id",
            "release_id",
            "binding_id",
            "day_engine_contract_id",
            "start_trade_date",
            "end_trade_date",
            "historical_source_id",
            "historical_source_sha256",
            "calendar_snapshot_sha256",
            "status",
            "next_trade_date",
            "completed_trade_date",
            "live_release_id",
            "live_binding_id",
            "activation_trade_date",
            "version",
            "failure_code",
            "failure_context",
            "created_by",
            "created_at",
            "updated_at",
        ],
        "selection.daily_selection_evidence": [
            "evidence_id",
            "target_trade_date",
            "cutoff_date",
            "package_id",
            "manifest_sha256",
            "release_id",
            "release_hash",
            "runtime_profile_version_id",
            "runtime_profile_hash",
            "source_type",
            "data_source",
            "candidate_count",
            "excluded_count",
            "artifact_hash",
            "evidence_payload_json",
            "created_at",
            "created_by",
        ],
        "paper_v2.execution_plan": [
            "plan_id",
            "strategy_id",
            "portfolio_id",
            "package_id",
            "release_id",
            "release_hash",
            "binding_id",
            "binding_hash",
            "selection_evidence_id",
            "selection_evidence_hash",
            "target_trade_date",
            "execution_policy_version_id",
            "execution_policy_sha256",
            "tail_policy_version_id",
            "tail_policy_sha256",
            "intent_count",
            "trading_rule_decision_count",
            "plan_payload_json",
            "plan_hash",
            "created_at",
        ],
        "paper_v2.simulation_daily_run": [
            "run_id",
            "trade_date",
            "strategy_id",
            "broker_backend",
            "package_id",
            "manifest_sha256",
            "release_id",
            "release_hash",
            "binding_id",
            "binding_hash",
            "account_group_id",
            "strategy_slot_id",
            "selection_evidence_id",
            "selection_artifact_hash",
            "execution_plan_id",
            "execution_plan_hash",
            "status",
            "run_payload_json",
            "created_at",
            "updated_at",
        ],
    }

    migration_ddl = "\n".join(
        [
            TRADING_CORE_MIGRATION.read_text(encoding="utf-8"),
                ACCOUNT_SLOT_MIGRATION.read_text(encoding="utf-8"),
                LOCALSIM_SUCCESSOR_MIGRATION.read_text(encoding="utf-8"),
                LOCALSIM_CUTOVER_BRIDGE_MIGRATION.read_text(encoding="utf-8"),
        ]
    )
    bootstrap_ddl = "\n".join(init_trading_core_v2_schema.iter_ddl())
    for ddl in (migration_ddl, bootstrap_ddl):
        for table, columns in expected.items():
            assert f"CREATE TABLE IF NOT EXISTS {table}" in ddl
            assert f"COMMENT ON TABLE {table}" in ddl
            for column in columns:
                assert f"COMMENT ON COLUMN {table}.{column}" in ddl
