from __future__ import annotations

from typing import Any


class AdvisoryModelingError(RuntimeError):
    """Typed, visible failure for Advisory modeling contracts and artifacts."""

    def __init__(
        self,
        reason_code: str,
        message: str,
        *,
        context: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.reason_code = reason_code
        self.context = dict(context or {})


MODEL_REASON_CODES = (
    "MODEL_CONTRACT_NOT_AVAILABLE",
    "MODEL_STYLE_PROFILE_MISMATCH",
    "MODEL_DATASET_SNAPSHOT_NOT_SEALED",
    "MODEL_DATASET_WINDOW_INSUFFICIENT",
    "MODEL_FEATURE_CLOSURE_INCOMPLETE",
    "MODEL_FEATURE_SNAPSHOT_INCOMPLETE",
    "MODEL_FEATURE_QUERY_REGISTRY_MISMATCH",
    "MODEL_LABEL_CLOSURE_INCOMPLETE",
    "MODEL_PIT_VINTAGE_CONFLICT",
    "MODEL_MARKET_REGIME_UNAVAILABLE",
    "MODEL_SPLIT_PLAN_MISMATCH",
    "MODEL_TRAINING_REQUIRES_WSL",
    "MODEL_TRAINING_ENVIRONMENT_MISMATCH",
    "MODEL_EXPERIMENT_REGISTRY_MISMATCH",
    "MODEL_SELECTION_NOT_UNIQUE",
    "MODEL_BUNDLE_INCOMPLETE",
    "MODEL_BUNDLE_HASH_MISMATCH",
    "MODEL_EXACT_RETRY_CONFLICT",
    "MODEL_NO_FORMAL_OOS",
    "MODEL_OOS_SAMPLE_INSUFFICIENT",
    "MODEL_OOS_THRESHOLD_NOT_MET",
    "MODEL_INFERENCE_INPUT_MISMATCH",
    "MODEL_SHADOW_WRITE_FAILED",
)

(
    REASON_CONTRACT_NOT_AVAILABLE,
    REASON_STYLE_PROFILE_MISMATCH,
    REASON_DATASET_SNAPSHOT_NOT_SEALED,
    REASON_DATASET_WINDOW_INSUFFICIENT,
    REASON_FEATURE_CLOSURE_INCOMPLETE,
    REASON_FEATURE_SNAPSHOT_INCOMPLETE,
    REASON_FEATURE_QUERY_REGISTRY_MISMATCH,
    REASON_LABEL_CLOSURE_INCOMPLETE,
    REASON_PIT_VINTAGE_CONFLICT,
    REASON_MARKET_REGIME_UNAVAILABLE,
    REASON_SPLIT_PLAN_MISMATCH,
    REASON_TRAINING_REQUIRES_WSL,
    REASON_TRAINING_ENVIRONMENT_MISMATCH,
    REASON_EXPERIMENT_REGISTRY_MISMATCH,
    REASON_SELECTION_NOT_UNIQUE,
    REASON_BUNDLE_INCOMPLETE,
    REASON_BUNDLE_HASH_MISMATCH,
    REASON_EXACT_RETRY_CONFLICT,
    REASON_NO_FORMAL_OOS,
    REASON_OOS_SAMPLE_INSUFFICIENT,
    REASON_OOS_THRESHOLD_NOT_MET,
    REASON_INFERENCE_INPUT_MISMATCH,
    REASON_SHADOW_WRITE_FAILED,
) = MODEL_REASON_CODES
