-- Autonomous market data sync target/attempt status source.
-- This migration is passive DDL only; it does not modify scheduler or sync-engine behavior.

CREATE SCHEMA IF NOT EXISTS market;

CREATE TABLE IF NOT EXISTS market.data_sync_targets (
    target_id TEXT PRIMARY KEY,
    dataset TEXT NOT NULL,
    data_source TEXT NOT NULL,
    target_date DATE,
    target_scope JSONB NOT NULL DEFAULT '{}'::jsonb,
    target_key_sha256 TEXT NOT NULL,
    target_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (target_status IN ('pending', 'retry', 'final_blocked', 'reconciled')),
    priority INTEGER NOT NULL DEFAULT 100 CHECK (priority >= 0),
    required_before TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    expected_rows BIGINT CHECK (expected_rows IS NULL OR expected_rows >= 0),
    observed_rows BIGINT CHECK (observed_rows IS NULL OR observed_rows >= 0),
    data_max_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_attempt_id TEXT,
    last_attempt_status TEXT
        CHECK (last_attempt_status IS NULL OR last_attempt_status IN ('started', 'failed', 'retry', 'final_blocked', 'reconciled')),
    last_error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reconciled_at TIMESTAMPTZ,
    blocked_at TIMESTAMPTZ,
    UNIQUE (dataset, data_source, target_key_sha256)
);

CREATE TABLE IF NOT EXISTS market.data_sync_attempts (
    attempt_id TEXT PRIMARY KEY,
    target_id TEXT NOT NULL REFERENCES market.data_sync_targets(target_id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    status TEXT NOT NULL
        CHECK (status IN ('started', 'failed', 'retry', 'final_blocked', 'reconciled')),
    trigger_source TEXT,
    worker_id TEXT,
    run_id TEXT,
    job_id TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    rows_written BIGINT CHECK (rows_written IS NULL OR rows_written >= 0),
    rows_observed BIGINT CHECK (rows_observed IS NULL OR rows_observed >= 0),
    coverage_ratio NUMERIC(12, 8) CHECK (coverage_ratio IS NULL OR (coverage_ratio >= 0 AND coverage_ratio <= 1.5)),
    data_max_at TIMESTAMPTZ,
    error_message TEXT,
    retry_after TIMESTAMPTZ,
    context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (target_id, attempt_no)
);

CREATE INDEX IF NOT EXISTS idx_data_sync_targets_fillable
    ON market.data_sync_targets(target_status, next_retry_at, priority, required_before);
CREATE INDEX IF NOT EXISTS idx_data_sync_targets_dataset_date
    ON market.data_sync_targets(dataset, data_source, target_date);
CREATE INDEX IF NOT EXISTS idx_data_sync_attempts_target
    ON market.data_sync_attempts(target_id, attempt_no DESC);
CREATE INDEX IF NOT EXISTS idx_data_sync_attempts_status
    ON market.data_sync_attempts(status, created_at DESC);

COMMENT ON TABLE market.data_sync_targets IS 'Passive AIstock status source for desired market data sync targets that may need initial fill, retry, final blocking, or reconciliation.';
COMMENT ON COLUMN market.data_sync_targets.target_id IS 'Stable target identifier generated by the repository, normally dst_ plus the target_key_sha256 prefix.';
COMMENT ON COLUMN market.data_sync_targets.dataset IS 'Logical market dataset key requiring synchronization, for example suspend_d, stk_limit, kline_daily_raw, or a future dataset.';
COMMENT ON COLUMN market.data_sync_targets.data_source IS 'Expected source/provider or process for this target, for example tushare, tdx_api, qlib_export, or manual_backfill.';
COMMENT ON COLUMN market.data_sync_targets.target_date IS 'Optional trading date or dataset date for date-granular targets; NULL when target_scope defines a range or non-date scope.';
COMMENT ON COLUMN market.data_sync_targets.target_scope IS 'Canonical JSON object describing the sync scope beyond target_date, such as date range, symbol list, table name, or partition key.';
COMMENT ON COLUMN market.data_sync_targets.target_key_sha256 IS 'SHA-256 digest of dataset, data_source, target_date, and canonical target_scope used for idempotent upsert.';
COMMENT ON COLUMN market.data_sync_targets.target_status IS 'Current target lifecycle: pending means fillable, retry means fillable after next_retry_at, final_blocked means no more automatic attempts, reconciled means target is satisfied.';
COMMENT ON COLUMN market.data_sync_targets.priority IS 'Lower numeric priority is selected earlier by future consumers when listing fillable targets.';
COMMENT ON COLUMN market.data_sync_targets.required_before IS 'Optional operational deadline by which this target should be reconciled before data-readiness gates consume it.';
COMMENT ON COLUMN market.data_sync_targets.next_retry_at IS 'Earliest timestamp when a retry target should be considered fillable again; NULL means immediately eligible.';
COMMENT ON COLUMN market.data_sync_targets.expected_rows IS 'Optional expected usable row count for the target scope, used for coverage checks when known.';
COMMENT ON COLUMN market.data_sync_targets.observed_rows IS 'Latest observed usable row count after an attempt or reconciliation check.';
COMMENT ON COLUMN market.data_sync_targets.data_max_at IS 'Latest source-data timestamp covered by this target, mainly for intraday or timestamped datasets; NULL for date-only targets.';
COMMENT ON COLUMN market.data_sync_targets.attempt_count IS 'Count of recorded attempts associated with this target in market.data_sync_attempts.';
COMMENT ON COLUMN market.data_sync_targets.last_attempt_id IS 'Latest attempt_id recorded against this target, denormalized for fast status display.';
COMMENT ON COLUMN market.data_sync_targets.last_attempt_status IS 'Latest attempt status copied from market.data_sync_attempts.status for fast filtering and diagnostics.';
COMMENT ON COLUMN market.data_sync_targets.last_error_message IS 'Latest provider, validation, or persistence error message associated with this target.';
COMMENT ON COLUMN market.data_sync_targets.metadata IS 'Additional JSON context for operators and future automation, such as owning module, policy version, or source table.';
COMMENT ON COLUMN market.data_sync_targets.created_at IS 'Timestamp when this target row was first created.';
COMMENT ON COLUMN market.data_sync_targets.updated_at IS 'Timestamp when this target row was last updated by repository/service operations.';
COMMENT ON COLUMN market.data_sync_targets.reconciled_at IS 'Timestamp when target_status was last marked reconciled.';
COMMENT ON COLUMN market.data_sync_targets.blocked_at IS 'Timestamp when target_status was last marked final_blocked.';

COMMENT ON TABLE market.data_sync_attempts IS 'Append-only attempt ledger for market.data_sync_targets; records outcomes without executing scheduler or sync-engine logic.';
COMMENT ON COLUMN market.data_sync_attempts.attempt_id IS 'Stable attempt identifier generated by caller or repository for one recorded sync or reconciliation attempt.';
COMMENT ON COLUMN market.data_sync_attempts.target_id IS 'Target being attempted; references market.data_sync_targets.target_id.';
COMMENT ON COLUMN market.data_sync_attempts.attempt_no IS 'Monotonic attempt sequence number within a target, assigned by the repository.';
COMMENT ON COLUMN market.data_sync_attempts.status IS 'Attempt lifecycle outcome: started, failed, retry, final_blocked, or reconciled.';
COMMENT ON COLUMN market.data_sync_attempts.trigger_source IS 'Human or automation source that triggered the attempt record, for example manual, readiness_gate, scheduler_probe, or backfill_tool.';
COMMENT ON COLUMN market.data_sync_attempts.worker_id IS 'Optional worker, process, host, or agent identifier that performed or observed the attempt.';
COMMENT ON COLUMN market.data_sync_attempts.run_id IS 'Optional external run identifier from a scheduler, validation run, or sync workflow.';
COMMENT ON COLUMN market.data_sync_attempts.job_id IS 'Optional external ingestion job identifier; stored as text to accept UUID or non-UUID job ids from multiple producers.';
COMMENT ON COLUMN market.data_sync_attempts.started_at IS 'Timestamp when the attempt started if known.';
COMMENT ON COLUMN market.data_sync_attempts.finished_at IS 'Timestamp when the attempt finished if known.';
COMMENT ON COLUMN market.data_sync_attempts.rows_written IS 'Rows written or touched by this attempt; NULL when unknown or not applicable.';
COMMENT ON COLUMN market.data_sync_attempts.rows_observed IS 'Usable rows observed after this attempt; NULL when unknown.';
COMMENT ON COLUMN market.data_sync_attempts.coverage_ratio IS 'Optional rows_observed divided by expected rows; 1.0 means exact expected coverage when expected rows are known.';
COMMENT ON COLUMN market.data_sync_attempts.data_max_at IS 'Maximum source-data timestamp observed by this attempt for timestamped datasets.';
COMMENT ON COLUMN market.data_sync_attempts.error_message IS 'Provider, validation, persistence, or policy error captured for failed, retry, or final_blocked attempts.';
COMMENT ON COLUMN market.data_sync_attempts.retry_after IS 'Suggested earliest retry time emitted by this attempt; copied to the target for retry outcomes.';
COMMENT ON COLUMN market.data_sync_attempts.context_json IS 'Additional JSON context such as request parameters, source response summary, quality flags, or reconciliation notes.';
COMMENT ON COLUMN market.data_sync_attempts.created_at IS 'Timestamp when this attempt row was inserted into the ledger.';
