-- Paper v2 MiniQMT autonomous auto-run portfolio configuration.
--
-- This migration is explicit DDL only. Business services must not create these
-- objects implicitly. Apply it before enabling auto-run in production.

ALTER TABLE paper_v2.portfolio
    ADD COLUMN IF NOT EXISTS auto_run_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE paper_v2.portfolio
    ADD COLUMN IF NOT EXISTS auto_run_config JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE paper_v2.portfolio
    ADD COLUMN IF NOT EXISTS auto_run_config_sha256 TEXT;

ALTER TABLE paper_v2.portfolio
    ADD COLUMN IF NOT EXISTS auto_run_updated_at TIMESTAMPTZ;

ALTER TABLE paper_v2.portfolio
    ADD COLUMN IF NOT EXISTS auto_run_updated_by TEXT;

COMMENT ON TABLE paper_v2.portfolio IS 'Paper Trading v2 portfolio freezing one StrategyPackage alpha-core manifest plus portfolio-level runtime state. Auto-run columns are Paper v2 runtime configuration, not StrategyPackage frozen manifest content.';
COMMENT ON COLUMN paper_v2.portfolio.auto_run_enabled IS 'Whether this portfolio is enrolled in Paper v2 autonomous scheduler recovery and daily runtime execution. False means normal manual/session-driven operation.';
COMMENT ON COLUMN paper_v2.portfolio.auto_run_config IS 'Canonical JSONB portfolio runtime config for autonomous execution, schema paper_v2_auto_run_v1; contains broker account, session, calendar, trade-window, selection, HMM, retry, reconciliation and UI policy settings outside StrategyPackage manifest.';
COMMENT ON COLUMN paper_v2.portfolio.auto_run_config_sha256 IS 'SHA-256 digest of canonical auto_run_config JSON used for audit, idempotency, and same-day artifact/cache reuse; NULL when auto-run was never configured.';
COMMENT ON COLUMN paper_v2.portfolio.auto_run_updated_at IS 'Timestamp when portfolio auto-run settings were last changed by an operator or coordinator; NULL when never configured.';
COMMENT ON COLUMN paper_v2.portfolio.auto_run_updated_by IS 'Actor or system id that last changed auto-run settings, for example operator, API user, or auto_run_coordinator.';

CREATE TABLE IF NOT EXISTS paper_v2.broker_account_binding (
    binding_id TEXT PRIMARY KEY,
    broker_backend TEXT NOT NULL CHECK (broker_backend IN ('local_sim', 'minqmt_sim')),
    broker_mode TEXT NOT NULL,
    broker_account_id TEXT NOT NULL,
    account_group_id TEXT,
    strategy_slot_id TEXT,
    portfolio_id TEXT NOT NULL REFERENCES paper_v2.portfolio(portfolio_id),
    binding_status TEXT NOT NULL CHECK (binding_status IN ('ACTIVE', 'PAUSED', 'RETIRED')),
    allocation_mode TEXT NOT NULL DEFAULT 'exclusive_account',
    initial_cash NUMERIC(20, 6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by TEXT
);

ALTER TABLE paper_v2.broker_account_binding
    ADD COLUMN IF NOT EXISTS account_group_id TEXT,
    ADD COLUMN IF NOT EXISTS strategy_slot_id TEXT;

COMMENT ON TABLE paper_v2.broker_account_binding IS 'Paper v2 broker account binding ledger for local_sim virtual portfolios, legacy exclusive MiniQMT bindings, and MiniQMT account_group_slots strategy-slot bindings.';
COMMENT ON COLUMN paper_v2.broker_account_binding.binding_id IS 'Stable binding identifier generated by Paper v2 when a portfolio is linked to a broker account for auto-run.';
COMMENT ON COLUMN paper_v2.broker_account_binding.broker_backend IS 'Broker backend for the account binding, currently local_sim or minqmt_sim; MiniQMT auto-run creation only uses minqmt_sim.';
COMMENT ON COLUMN paper_v2.broker_account_binding.broker_mode IS 'Broker account mode such as SIM. Paper v2 auto-run must not create live trading bindings in this phase.';
COMMENT ON COLUMN paper_v2.broker_account_binding.broker_account_id IS 'External broker account identifier, for MiniQMT usually MINIQMT_ACCOUNT_ID; account_group_slots may have multiple active strategy slots under the same value.';
COMMENT ON COLUMN paper_v2.broker_account_binding.account_group_id IS 'MiniQMT shared simulation account group id for Paper v2 account_group_slots auto-run bindings.';
COMMENT ON COLUMN paper_v2.broker_account_binding.strategy_slot_id IS 'Paper v2 strategy slot id under the MiniQMT account group; defaults to portfolio_id for N=1/N>1 compatibility.';
COMMENT ON COLUMN paper_v2.broker_account_binding.portfolio_id IS 'Paper v2 portfolio owning this account binding. The portfolio keeps StrategyPackage alpha-core identity separately.';
COMMENT ON COLUMN paper_v2.broker_account_binding.binding_status IS 'Lifecycle status: ACTIVE participates in uniqueness and auto-run, PAUSED is temporarily disabled, RETIRED is historical.';
COMMENT ON COLUMN paper_v2.broker_account_binding.allocation_mode IS 'Capital/allocation isolation mode. account_group_slots allows multiple Paper v2 strategy slots under one MiniQMT SIM account; exclusive_account remains legacy-only.';
COMMENT ON COLUMN paper_v2.broker_account_binding.initial_cash IS 'Optional operator-entered starting capital reference in account currency. MiniQMT remains the authority for real cash and positions.';
COMMENT ON COLUMN paper_v2.broker_account_binding.created_at IS 'Timestamp when this binding row was created.';
COMMENT ON COLUMN paper_v2.broker_account_binding.updated_at IS 'Timestamp when this binding row was last updated.';
COMMENT ON COLUMN paper_v2.broker_account_binding.created_by IS 'Actor or system id that created this broker account binding.';

UPDATE paper_v2.broker_account_binding
SET
    account_group_id = COALESCE(
        NULLIF(account_group_id, ''),
        'ag_minqmt_' || COALESCE(NULLIF(btrim(regexp_replace(broker_account_id, '[^A-Za-z0-9_]+', '_', 'g'), '_'), ''), 'unassigned') || '_sim'
    ),
    strategy_slot_id = COALESCE(NULLIF(strategy_slot_id, ''), portfolio_id)
WHERE broker_backend = 'minqmt_sim'
  AND allocation_mode = 'account_group_slots'
  AND (NULLIF(account_group_id, '') IS NULL OR NULLIF(strategy_slot_id, '') IS NULL);

DROP INDEX IF EXISTS paper_v2.idx_paper_v2_broker_account_binding_active_account;

CREATE INDEX IF NOT EXISTS idx_paper_v2_portfolio_auto_run
    ON paper_v2.portfolio(auto_run_enabled, status, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_v2_broker_account_binding_active_legacy_account
    ON paper_v2.broker_account_binding(broker_backend, broker_mode, broker_account_id)
    WHERE binding_status = 'ACTIVE' AND allocation_mode <> 'account_group_slots';

CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_v2_broker_account_binding_active_account_slot
    ON paper_v2.broker_account_binding(broker_backend, broker_mode, broker_account_id, account_group_id, strategy_slot_id)
    WHERE binding_status = 'ACTIVE' AND allocation_mode = 'account_group_slots';

CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_v2_broker_account_binding_active_portfolio
    ON paper_v2.broker_account_binding(portfolio_id)
    WHERE binding_status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_paper_v2_broker_account_binding_account_group
    ON paper_v2.broker_account_binding(broker_backend, broker_mode, broker_account_id, account_group_id, updated_at DESC)
    WHERE binding_status = 'ACTIVE' AND allocation_mode = 'account_group_slots';

CREATE INDEX IF NOT EXISTS idx_paper_v2_broker_account_binding_portfolio
    ON paper_v2.broker_account_binding(portfolio_id, binding_status, updated_at DESC);
