CREATE SCHEMA IF NOT EXISTS strategy_pkg;

CREATE TABLE IF NOT EXISTS strategy_pkg.package_runtime_variant (
    variant_id TEXT PRIMARY KEY,
    package_id TEXT NOT NULL REFERENCES strategy_pkg.package(package_id) ON DELETE RESTRICT,
    manifest_sha256 TEXT NOT NULL,
    locked_core_hash TEXT NOT NULL,
    variant_name TEXT NOT NULL,
    variant_kind TEXT NOT NULL,
    variant_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    variant_hash TEXT NOT NULL,
    validation_status TEXT NOT NULL DEFAULT 'DRAFT',
    paper_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    validation_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT package_runtime_variant_kind_check CHECK (variant_kind IN ('strategy_config', 'execution_policy', 'risk_policy', 'hmm_overlay', 'combined')),
    CONSTRAINT package_runtime_variant_validation_status_check CHECK (validation_status IN ('DRAFT', 'VALIDATION_PENDING', 'VALIDATION_PASSED', 'VALIDATION_FAILED', 'RETIRED')),
    CONSTRAINT package_runtime_variant_paper_candidate_check CHECK (paper_candidate = FALSE OR validation_status = 'VALIDATION_PASSED')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_package_runtime_variant_hash
    ON strategy_pkg.package_runtime_variant(package_id, variant_hash);
CREATE INDEX IF NOT EXISTS idx_package_runtime_variant_status
    ON strategy_pkg.package_runtime_variant(package_id, validation_status, paper_candidate);
CREATE INDEX IF NOT EXISTS idx_package_runtime_variant_core
    ON strategy_pkg.package_runtime_variant(package_id, manifest_sha256, locked_core_hash);

COMMENT ON TABLE strategy_pkg.package_runtime_variant IS 'Governed runtime variants around a frozen StrategyPackage core; variants may change strategy, execution, HMM, or risk runtime settings but must not mutate frozen factors, model assets, or alpha core.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.variant_id IS 'Stable runtime variant identifier generated by AIstock, prefixed rtv_.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.package_id IS 'Frozen StrategyPackage identifier that owns this runtime variant.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.manifest_sha256 IS 'SHA256 of the frozen StrategyPackage manifest at variant creation time; used to block silent manifest/core mutation.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.locked_core_hash IS 'SHA256 of normalized frozen alpha/model/factor core fields; runtime variants with different runtime settings must keep this hash unchanged.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.variant_name IS 'Operator-facing runtime variant display name.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.variant_kind IS 'Runtime variant kind: strategy_config, execution_policy, risk_policy, hmm_overlay, or combined.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.variant_config IS 'JSONB runtime-only overrides; forbidden to contain factor_set, model_asset, alpha_components, manifest_json, or manifest_sha256.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.variant_hash IS 'SHA256 of package_id, manifest_sha256, locked_core_hash, variant_kind, and normalized variant_config.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.validation_status IS 'Variant validation lifecycle status; Paper candidate requires VALIDATION_PASSED.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.paper_candidate IS 'Whether this validated variant may be considered for Paper candidate flows; false until validation passes.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.validation_evidence IS 'JSONB evidence for variant validation runs, commands, metrics, artifact hashes, and review notes.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.created_by IS 'Operator, service, or automation that created the runtime variant.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.created_at IS 'Database timestamp when the runtime variant row was inserted.';
COMMENT ON COLUMN strategy_pkg.package_runtime_variant.updated_at IS 'Database timestamp when validation status or evidence was last changed.';
