CREATE TABLE IF NOT EXISTS strategy_pkg.multi_alpha_paper_admission (
    admission_id TEXT PRIMARY KEY,
    package_id TEXT NOT NULL REFERENCES strategy_pkg.package(package_id) ON DELETE CASCADE,
    manifest_sha256 TEXT NOT NULL,
    broker_backend TEXT NOT NULL,
    runtime_variant TEXT NOT NULL,
    eligible BOOLEAN NOT NULL DEFAULT FALSE,
    dry_run_run_id TEXT NOT NULL,
    artifact_shas JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    validated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    validated_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT multi_alpha_paper_admission_broker_backend_chk CHECK (broker_backend IN ('local_sim', 'minqmt_sim')),
    CONSTRAINT multi_alpha_paper_admission_runtime_variant_chk CHECK (runtime_variant ~ '^top_k=(25|50)$'),
    CONSTRAINT multi_alpha_paper_admission_manifest_sha_chk CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT multi_alpha_paper_admission_dry_run_chk CHECK (length(dry_run_run_id) > 0),
    CONSTRAINT multi_alpha_paper_admission_validated_by_chk CHECK (length(validated_by) > 0),
    CONSTRAINT multi_alpha_paper_admission_unique UNIQUE (package_id, manifest_sha256, broker_backend, runtime_variant)
);

CREATE INDEX IF NOT EXISTS idx_multi_alpha_paper_admission_lookup
ON strategy_pkg.multi_alpha_paper_admission(package_id, manifest_sha256, broker_backend, runtime_variant)
WHERE eligible = TRUE;

COMMENT ON TABLE strategy_pkg.multi_alpha_paper_admission IS 'Manifest-external admission ledger for MULTI_ALPHA StrategyPackage Paper v2 readiness; preserves frozen manifest sha and gates broker-specific runtime variants.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.admission_id IS 'Stable admission identifier prefixed mapa_, derived from canonical dry-run evidence.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.package_id IS 'MULTI_ALPHA parent StrategyPackage id under admission; SINGLE_ALPHA packages do not write this table.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.manifest_sha256 IS 'Frozen parent manifest sha256 bound to this admission; manifest changes require a new dry-run.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.broker_backend IS 'Paper v2 broker backend scoped by admission, currently local_sim or minqmt_sim; local_sim evidence must not admit MiniQMT.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.runtime_variant IS 'Runtime variant key such as top_k=25 or top_k=50, aligned with selection runtime profile top_k.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.eligible IS 'True only when the broker/runtime dry-run passed; eligibility logic ignores false rows.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.dry_run_run_id IS 'Dry-run evidence id generated by MultiAlphaPaperDryRunValidator; this is not a persisted PaperRun or broker order run.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.artifact_shas IS 'JSONB schema multi_alpha_paper_admission_artifacts_v1: component, weight, combined, targets, order preview, and deterministic replay hashes.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.evidence_json IS 'JSONB schema multi_alpha_paper_admission_evidence_v1: trade date, runtime hash, target preview, order preview, source metadata, and determinism context.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.validated_at IS 'Timestamp when the dry-run validation succeeded.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.validated_by IS 'Operator or API actor that requested the dry-run validation.';
COMMENT ON COLUMN strategy_pkg.multi_alpha_paper_admission.created_at IS 'Timestamp when the admission row was inserted.';
