-- Phase 7 StrategyPackage validation modes foundation.
CREATE SCHEMA IF NOT EXISTS strategy_pkg;

CREATE TABLE IF NOT EXISTS strategy_pkg.package_validation_run (
    validation_run_id TEXT PRIMARY KEY,
    package_id TEXT NOT NULL REFERENCES strategy_pkg.package(package_id),
    manifest_sha256 TEXT NOT NULL,
    runtime_variant_id TEXT NULL,
    runtime_variant_hash TEXT NULL,
    validation_type TEXT NOT NULL,
    retrain_mode TEXT NOT NULL,
    model_version_id TEXT NULL,
    seed_policy TEXT NULL,
    random_seed BIGINT NULL,
    source_data_version TEXT NULL,
    target_data_version TEXT NULL,
    backtest_start DATE NULL,
    backtest_end DATE NULL,
    status TEXT NOT NULL DEFAULT 'REQUESTED',
    metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    artifact_manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    reproducibility_level TEXT NOT NULL DEFAULT 'UNKNOWN',
    created_by TEXT NOT NULL DEFAULT 'aistock_api',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT package_validation_type_check CHECK (validation_type IN (
        'original_fixed_weight',
        'original_retrain',
        'latest_fixed_weight',
        'latest_retrain',
        'walk_forward_rolling',
        'runtime_variant_backtest'
    )),
    CONSTRAINT package_validation_retrain_mode_check CHECK (retrain_mode IN (
        'no_retrain',
        'fixed_seed_retrain',
        'multi_seed_retrain',
        'rolling_retrain'
    )),
    CONSTRAINT package_validation_status_check CHECK (status IN (
        'REQUESTED',
        'RUNNING',
        'PASSED',
        'FAILED',
        'CANCELLED'
    )),
    CONSTRAINT package_validation_reproducibility_check CHECK (reproducibility_level IN (
        'UNKNOWN',
        'STRICT',
        'STATISTICALLY_CLOSE',
        'NON_DETERMINISTIC',
        'NOT_APPLICABLE'
    )),
    CONSTRAINT package_validation_backtest_window_check CHECK (
        backtest_start IS NULL OR backtest_end IS NULL OR backtest_end >= backtest_start
    ),
    CONSTRAINT package_validation_terminal_completed_check CHECK (
        status NOT IN ('PASSED', 'FAILED', 'CANCELLED') OR completed_at IS NOT NULL
    ),
    CONSTRAINT package_validation_passed_evidence_check CHECK (
        status <> 'PASSED'
        OR (metrics_json <> '{}'::jsonb AND artifact_manifest_json <> '{}'::jsonb)
    ),
    CONSTRAINT package_validation_runtime_variant_check CHECK (
        (validation_type = 'runtime_variant_backtest' AND runtime_variant_id IS NOT NULL AND runtime_variant_hash IS NOT NULL)
        OR (validation_type <> 'runtime_variant_backtest' AND runtime_variant_id IS NULL AND runtime_variant_hash IS NULL)
    ),
    CONSTRAINT package_validation_latest_data_check CHECK (
        validation_type NOT IN ('latest_fixed_weight', 'latest_retrain', 'walk_forward_rolling')
        OR target_data_version IS NOT NULL
    ),
    CONSTRAINT package_validation_fixed_weight_check CHECK (
        validation_type NOT IN ('original_fixed_weight', 'latest_fixed_weight', 'runtime_variant_backtest')
        OR retrain_mode = 'no_retrain'
    ),
    CONSTRAINT package_validation_retrain_seed_check CHECK (
        validation_type NOT IN ('original_retrain', 'latest_retrain', 'walk_forward_rolling')
        OR (retrain_mode <> 'no_retrain' AND seed_policy IS NOT NULL)
    ),
    CONSTRAINT package_validation_walk_forward_check CHECK (
        validation_type <> 'walk_forward_rolling'
        OR (
            retrain_mode = 'rolling_retrain'
            AND COALESCE(
                jsonb_typeof(evidence_json->'windows') = 'array'
                AND jsonb_array_length(evidence_json->'windows') > 0,
                FALSE
            )
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_package_validation_run_package
    ON strategy_pkg.package_validation_run(package_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_package_validation_run_type_status
    ON strategy_pkg.package_validation_run(package_id, validation_type, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_package_validation_run_variant
    ON strategy_pkg.package_validation_run(package_id, runtime_variant_id, created_at DESC)
    WHERE runtime_variant_id IS NOT NULL;

COMMENT ON TABLE strategy_pkg.package_validation_run IS 'Append-only StrategyPackage validation runs for original retest, latest-data fixed-weight, latest-data retrain, walk-forward rolling, and runtime-variant validation evidence.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.validation_run_id IS 'Stable validation run identifier generated by AIstock, prefixed vr_.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.package_id IS 'Frozen StrategyPackage identifier being validated.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.manifest_sha256 IS 'SHA256 of the frozen StrategyPackage manifest at validation time; used to prevent silent manifest mutation.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.runtime_variant_id IS 'Optional runtime variant identifier; only set for runtime_variant_backtest validation runs.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.runtime_variant_hash IS 'Optional runtime variant hash captured for exact runtime-variant evidence.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.validation_type IS 'Validation mode: original_fixed_weight, original_retrain, latest_fixed_weight, latest_retrain, walk_forward_rolling, or runtime_variant_backtest.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.retrain_mode IS 'Retrain behavior: no_retrain, fixed_seed_retrain, multi_seed_retrain, or rolling_retrain.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.model_version_id IS 'Optional model version produced or used by this validation run; retrain validations must not overwrite frozen package weights.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.seed_policy IS 'Seed policy declared for retrain or walk-forward validation evidence.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.random_seed IS 'Optional concrete seed used by the validation run when applicable.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.source_data_version IS 'Original or baseline data version used as the source comparison context.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.target_data_version IS 'Latest or target data version used by latest-data and walk-forward validation.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.backtest_start IS 'Inclusive validation backtest start date when applicable.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.backtest_end IS 'Inclusive validation backtest end date when applicable.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.status IS 'Validation run lifecycle status: REQUESTED, RUNNING, PASSED, FAILED, or CANCELLED.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.metrics_json IS 'JSONB validation metrics stored separately from original QE metrics.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.artifact_manifest_json IS 'JSONB artifact manifest for validation outputs; never overwrites frozen StrategyPackage manifest assets.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.evidence_json IS 'JSONB run evidence such as commands, windows, runner IDs, checksums, and review notes.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.reproducibility_level IS 'Reproducibility classification observed by this validation run.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.created_by IS 'Operator, service, or automation that recorded the validation run.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.created_at IS 'Database timestamp when the validation run row was inserted.';
COMMENT ON COLUMN strategy_pkg.package_validation_run.completed_at IS 'Completion timestamp required for terminal validation statuses.';
