-- Candidate StrategyPackage durable snapshot schema.
-- Explicit migration only: business services must not run this DDL implicitly.

CREATE SCHEMA IF NOT EXISTS strategy_pkg;

DO $$
BEGIN
    IF to_regclass('strategy_pkg.package') IS NOT NULL THEN
        ALTER TABLE strategy_pkg.package
            DROP CONSTRAINT IF EXISTS package_source_type_check;
        ALTER TABLE strategy_pkg.package
            ADD CONSTRAINT package_source_type_check
            CHECK (source_type IN ('qe_experiment', 'qe_evolution_loop', 'candidate_strategy_package'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS strategy_pkg.candidate_strategy_package (
    candidate_id TEXT PRIMARY KEY,
    candidate_version INTEGER NOT NULL DEFAULT 1 CHECK (candidate_version > 0),
    source_type TEXT NOT NULL CHECK (source_type IN ('qe_experiment', 'qe_evolution_loop', 'candidate_strategy_package')),
    source_id TEXT NOT NULL,
    source_task_id TEXT,
    source_loop_id TEXT,
    source_experiment_id TEXT,
    archive_run_id TEXT,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DELETED')),
    snapshot_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    factor_manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    model_manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    strategy_manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    metric_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    artifact_refs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    completeness_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    eligibility_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    audit_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_by TEXT,
    deleted_at TIMESTAMPTZ,
    delete_reason TEXT,
    UNIQUE (source_type, source_id, candidate_version)
);

CREATE INDEX IF NOT EXISTS idx_strategy_pkg_candidate_source
    ON strategy_pkg.candidate_strategy_package(source_type, source_id, status);

CREATE INDEX IF NOT EXISTS idx_strategy_pkg_candidate_status
    ON strategy_pkg.candidate_strategy_package(status, created_at DESC);

CREATE TABLE IF NOT EXISTS strategy_pkg.candidate_strategy_package_audit (
    audit_id BIGSERIAL PRIMARY KEY,
    candidate_id TEXT NOT NULL REFERENCES strategy_pkg.candidate_strategy_package(candidate_id) ON DELETE RESTRICT,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    context JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE strategy_pkg.candidate_strategy_package IS 'Durable, user-created Candidate StrategyPackage snapshots. These records are independent from original QE experiment/loop cleanup.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.candidate_id IS 'Stable Candidate StrategyPackage identifier generated by AIstock, prefixed csp_.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.source_type IS 'Original source type: qe_experiment, qe_evolution_loop, or candidate_strategy_package clone.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.source_id IS 'Source identifier copied as text; no FK is used so QE source deletion cannot cascade into candidates.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.archive_run_id IS 'Optional qe_archive.run identifier retained as an audit reference; not a cascading FK.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.snapshot_config_json IS 'Canonical config snapshot copied at manual add time.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.factor_manifest_json IS 'Factor list/order/version/hash snapshot; contains references, not factor value files.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.model_manifest_json IS 'Model entry/weight/seed/hyperparameter snapshot; contains refs and hashes, not weight files.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.strategy_manifest_json IS 'Daily strategy, minute execution, tail handling, and risk/cost config snapshot.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.artifact_refs_json IS 'Artifact URI/hash/size references only; large file payloads must stay outside PostgreSQL.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.completeness_json IS 'Asset completeness findings; missing legacy seed/hyperparams may block future live approval but not selection or paper simulation.';
COMMENT ON COLUMN strategy_pkg.candidate_strategy_package.eligibility_json IS 'Derived selection/paper/live eligibility explanation; live approval is reserved for future workflow.';
COMMENT ON TABLE strategy_pkg.candidate_strategy_package_audit IS 'Append-only audit events for Candidate StrategyPackage lifecycle actions.';
