-- Phase 1 Manual SOTA Promotion Review additive migration.
-- Draft only: do not execute against production DB until reviewed and scheduled.
-- Adds strategy_pkg.promotion_review for existing databases that predate the
-- trading_core_v2_schema.sql baseline.

CREATE SCHEMA IF NOT EXISTS strategy_pkg;

CREATE TABLE IF NOT EXISTS strategy_pkg.promotion_review (
    review_id TEXT PRIMARY KEY,
    source_type TEXT NOT NULL CHECK (source_type IN ('qe_experiment', 'qe_evolution_loop')),
    source_id TEXT NOT NULL,
    task_id TEXT,
    loop_id TEXT,
    experiment_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('AUTO_CANDIDATE', 'REVIEW_PENDING', 'REVIEW_REJECTED', 'SOTA_APPROVED')),
    requested_by TEXT NOT NULL,
    reviewer TEXT,
    review_reason TEXT,
    decision_reason TEXT,
    source_metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    audit_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    decided_at TIMESTAMPTZ,
    UNIQUE (source_type, source_id)
);

CREATE INDEX IF NOT EXISTS idx_strategy_pkg_promotion_review_status
    ON strategy_pkg.promotion_review(status, created_at DESC);

COMMENT ON TABLE strategy_pkg.promotion_review IS 'Manual SOTA promotion review ledger for QE experiments or evolution loops; REVIEW_PENDING is created by user action and does not imply approved SOTA or Paper eligibility.';
COMMENT ON COLUMN strategy_pkg.promotion_review.review_id IS 'Stable review identifier generated by AIstock promotion workflow, prefixed pr_.';
COMMENT ON COLUMN strategy_pkg.promotion_review.source_type IS 'Source object type for the candidate, currently qe_experiment or qe_evolution_loop.';
COMMENT ON COLUMN strategy_pkg.promotion_review.source_id IS 'Stable source object identifier; unique with source_type to make repeated manual requests idempotent.';
COMMENT ON COLUMN strategy_pkg.promotion_review.task_id IS 'Optional QE task id for evolution-loop sources, retained for audit and UI filtering.';
COMMENT ON COLUMN strategy_pkg.promotion_review.loop_id IS 'Optional QE evolution loop id in database form, usually {task_id}_Loop{N}.';
COMMENT ON COLUMN strategy_pkg.promotion_review.experiment_id IS 'Optional QE experiment id associated with the promoted source.';
COMMENT ON COLUMN strategy_pkg.promotion_review.status IS 'Promotion lifecycle status; AUTO_CANDIDATE is an unapproved automatic discovery, REVIEW_PENDING awaits human review, and SOTA_APPROVED requires explicit future approval.';
COMMENT ON COLUMN strategy_pkg.promotion_review.requested_by IS 'User, UI actor, or service identity that requested manual SOTA review.';
COMMENT ON COLUMN strategy_pkg.promotion_review.reviewer IS 'Human reviewer identity that made a future approval or rejection decision; NULL while pending.';
COMMENT ON COLUMN strategy_pkg.promotion_review.review_reason IS 'Requester-supplied reason or note captured when creating the review.';
COMMENT ON COLUMN strategy_pkg.promotion_review.decision_reason IS 'Reviewer-supplied approval or rejection rationale; NULL while pending.';
COMMENT ON COLUMN strategy_pkg.promotion_review.source_metrics_json IS 'Snapshot of source QE metrics at request time; display/audit evidence only, not recomputed by this table.';
COMMENT ON COLUMN strategy_pkg.promotion_review.audit_json IS 'Machine-readable audit context including workflow source, candidate state, non-approval flags, and Paper eligibility false by default.';
COMMENT ON COLUMN strategy_pkg.promotion_review.created_at IS 'Timestamp when the manual promotion review row was created.';
COMMENT ON COLUMN strategy_pkg.promotion_review.updated_at IS 'Timestamp when the promotion review row was last updated.';
COMMENT ON COLUMN strategy_pkg.promotion_review.decided_at IS 'Timestamp of a future human approval or rejection decision; NULL for AUTO_CANDIDATE or REVIEW_PENDING.';
