"""Official factor-value cache metadata helpers.

This module does not compute factor values or create realtime snapshots. Official
factor values are generated by OfficialFactorBatchComputeService from offline
backtest data and stored under rdagent_assets/factor_values.
"""
from __future__ import annotations

import json
import logging
import os
import threading
from datetime import datetime
from typing import Any, Dict, List, Optional

from ...db.pg_pool import get_conn

logger = logging.getLogger("aistock.quantevolver.factor_value_pipeline")

_PROJECT_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..")
)
_QE_FACTORS_DIR = os.path.join(_PROJECT_ROOT, "rdagent_assets", "qe_factors")


class FactorValuePipeline:
    """Read and validate the official offline factor-value cache."""

    def __init__(self, output_dir: Optional[str] = None):
        if output_dir is None:
            raise ValueError(
                "FactorValuePipeline requires an explicit output_dir under "
                "rdagent_assets/factor_values."
            )
        self._output_dir = output_dir
        self._meta_lock = threading.Lock()

    def get_computable_factors(
        self,
        limit: Optional[int] = None,
        factor_types: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """Return transformed factors that still have executable QE code."""
        conditions = ["transformation_status = 'SUCCESS'"]
        params: list = []

        if factor_types:
            placeholders = ",".join(["%s"] * len(factor_types))
            conditions.append(f"factor_type IN ({placeholders})")
            params.extend(factor_types)

        where = " AND ".join(conditions)
        sql = f"""
            SELECT factor_name, source, qe_code_path, factor_type,
                   last_transformation_at
            FROM aistock_factor_catalog
            WHERE {where}
            ORDER BY factor_name
        """
        if limit:
            sql += f" LIMIT {limit}"

        with get_conn() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, params or None)
                cols = [d[0] for d in cur.description]
                rows = cur.fetchall()

        results = []
        for row in rows:
            data = dict(zip(cols, row))
            code_path = data.get("qe_code_path")
            if code_path:
                abs_path = os.path.join(_PROJECT_ROOT, code_path)
                data["code_exists"] = os.path.isfile(abs_path)
            else:
                data["code_exists"] = False
            if data.get("last_transformation_at") and hasattr(
                data["last_transformation_at"], "isoformat"
            ):
                data["last_transformation_at"] = data[
                    "last_transformation_at"
                ].isoformat()
            results.append(data)

        return results

    def _single_dir(self) -> str:
        single_dir = os.path.join(self._output_dir, "single")
        os.makedirs(single_dir, exist_ok=True)
        return single_dir

    def _meta_path(self) -> str:
        return os.path.join(self._output_dir, "_meta.json")

    def _load_meta(self) -> Dict[str, Any]:
        meta_path = self._meta_path()
        with self._meta_lock:
            if os.path.isfile(meta_path):
                try:
                    with open(meta_path, "r", encoding="utf-8") as f:
                        return json.load(f)
                except Exception as exc:
                    logger.error("_meta.json parse failed: %s", exc)
                    raise RuntimeError(
                        f"_meta.json is corrupted: {meta_path}, error={exc}"
                    ) from exc
            return {"factors": {}}

    def _disk_single_files(self) -> Dict[str, str]:
        """Return disk-backed single-factor parquet files keyed by factor name."""
        single_dir = os.path.join(self._output_dir, "single")
        if not os.path.isdir(single_dir):
            return {}
        result: Dict[str, str] = {}
        for filename in os.listdir(single_dir):
            if not filename.endswith(".parquet") or filename.startswith("_"):
                continue
            factor_name = filename[:-8]
            result[factor_name] = os.path.join(single_dir, filename)
        return result

    def get_cache_inventory(self) -> Dict[str, Any]:
        """Return a read-only inventory for disk parquet files and meta entries.

        Disk parquet existence is the physical cache source of truth.  The meta
        registry is a contract layer used for hash/window/universe validation,
        so missing meta is reported as reconcile-required rather than no-cache.
        """
        meta = self._load_meta()
        factors = meta.get("factors", {}) if isinstance(meta.get("factors"), dict) else {}
        disk_files = self._disk_single_files()
        disk_names = set(disk_files)
        meta_names = set(factors)
        total_size_bytes = 0
        for path in disk_files.values():
            try:
                total_size_bytes += os.path.getsize(path)
            except OSError:
                continue

        def _first_meta_value(*keys: str) -> Any:
            for key in keys:
                value = meta.get(key)
                if value:
                    return value
            for entry in factors.values():
                if not isinstance(entry, dict):
                    continue
                for key in keys:
                    value = entry.get(key)
                    if value:
                        return value
            return None

        return {
            "cache_root": self._output_dir,
            "single_dir": os.path.join(self._output_dir, "single"),
            "meta_path": self._meta_path(),
            "disk_factor_count": len(disk_names),
            "meta_factor_count": len(meta_names),
            "orphan_parquet_count": len(disk_names - meta_names),
            "orphan_meta_count": len(meta_names - disk_names),
            "orphan_parquets": sorted(disk_names - meta_names),
            "orphan_meta_entries": sorted(meta_names - disk_names),
            "total_size_mb": round(total_size_bytes / 1024 / 1024, 1),
            "as_of_date": _first_meta_value("as_of_date"),
            "generated_at": meta.get("generated_at"),
            "date_range": _first_meta_value("date_range"),
            "data_source_mode": _first_meta_value("data_source_mode", "source_system"),
            "data_freshness_profile": _first_meta_value("data_freshness_profile"),
            "window_train_start": _first_meta_value("window_train_start"),
            "window_backtest_end": _first_meta_value("window_backtest_end"),
        }

    def validate_meta_integrity(self) -> Dict[str, Any]:
        """Return read-only consistency checks for single/*.parquet and _meta.json."""
        single_dir = os.path.join(self._output_dir, "single")
        meta_path = self._meta_path()
        disk_names = {
            f[:-8]
            for f in os.listdir(single_dir)
            if f.endswith(".parquet") and not f.startswith("_")
        } if os.path.isdir(single_dir) else set()

        if not os.path.isfile(meta_path):
            orphan_parquets = sorted(disk_names)
            return {
                "ok": False,
                "error": f"_meta.json does not exist: {meta_path}",
                "orphan_parquets": orphan_parquets,
                "orphan_meta_entries": [],
                "as_of_date_distribution": {},
                "top_level_as_of_date": None,
                "top_level_aod_mismatch": False,
                "incomplete_entries": [],
                "factor_count": 0,
                "disk_factor_count": len(disk_names),
                "meta_factor_count": 0,
                "orphan_parquet_count": len(orphan_parquets),
                "orphan_meta_count": 0,
                "meta_path": meta_path,
            }

        if not os.path.isdir(single_dir):
            meta = self._load_meta()
            factors = meta.get("factors", {}) if isinstance(meta.get("factors"), dict) else {}
            meta_names = set(factors.keys())
            return {
                "ok": False,
                "error": f"single cache directory does not exist: {single_dir}",
                "orphan_parquets": [],
                "orphan_meta_entries": sorted(meta_names),
                "as_of_date_distribution": {},
                "top_level_as_of_date": None,
                "top_level_aod_mismatch": False,
                "incomplete_entries": [],
                "factor_count": len(factors),
                "disk_factor_count": 0,
                "meta_factor_count": len(meta_names),
                "orphan_parquet_count": 0,
                "orphan_meta_count": len(meta_names),
                "meta_path": meta_path,
            }

        meta = self._load_meta()
        factors = meta.get("factors", {}) if isinstance(meta.get("factors"), dict) else {}
        top_aod = meta.get("as_of_date")

        meta_names = set(factors.keys())

        orphan_parquets = sorted(disk_names - meta_names)
        orphan_meta_entries = sorted(meta_names - disk_names)

        aod_dist: Dict[str, List[str]] = {}
        incomplete: List[str] = []
        required_fields = ("computed_at", "as_of_date", "rows", "date_range")
        for factor_name, entry in factors.items():
            aod = entry.get("as_of_date")
            aod_dist.setdefault(aod, []).append(factor_name)
            if any(not entry.get(key) for key in required_fields):
                incomplete.append(factor_name)

        top_mismatch = False
        if top_aod is not None and len(aod_dist) == 1:
            only_aod = next(iter(aod_dist.keys()))
            top_mismatch = only_aod != top_aod

        ok = (
            not orphan_parquets
            and not orphan_meta_entries
            and len(aod_dist) <= 1
            and not incomplete
            and not top_mismatch
            and len(factors) > 0
        )

        return {
            "ok": ok,
            "orphan_parquets": orphan_parquets,
            "orphan_meta_entries": orphan_meta_entries,
            "as_of_date_distribution": {key: len(value) for key, value in aod_dist.items()},
            "as_of_date_factor_sample": {key: value[:5] for key, value in aod_dist.items()},
            "top_level_as_of_date": top_aod,
            "top_level_aod_mismatch": top_mismatch,
            "incomplete_entries": incomplete,
            "factor_count": len(factors),
            "disk_factor_count": len(disk_names),
            "meta_factor_count": len(meta_names),
            "orphan_parquet_count": len(orphan_parquets),
            "orphan_meta_count": len(orphan_meta_entries),
            "meta_path": meta_path,
        }

    def get_cached_singles(self) -> List[Dict[str, Any]]:
        """Return cached single-factor parquet files and their metadata."""
        single_dir = os.path.join(self._output_dir, "single")
        if not os.path.isdir(single_dir):
            return []

        meta = self._load_meta()
        factors_meta = meta.get("factors", {})
        results = []

        for filename in sorted(os.listdir(single_dir)):
            if not filename.endswith(".parquet") or filename.startswith("_"):
                continue
            factor_name = filename[:-8]
            fpath = os.path.join(single_dir, filename)
            stat = os.stat(fpath)
            factor_meta = factors_meta.get(factor_name, {})
            results.append(
                {
                    "factor_name": factor_name,
                    "filename": filename,
                    "size_mb": round(stat.st_size / 1024 / 1024, 2),
                    "modified": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                    "computed_at": factor_meta.get("computed_at"),
                    "rows": factor_meta.get("rows"),
                    "date_range": factor_meta.get("date_range"),
                    "as_of_date": factor_meta.get("as_of_date"),
                }
            )

        return results

    def get_cache_status(self) -> Dict[str, Any]:
        """Return an overview of the official factor-value cache."""
        cached = self.get_cached_singles()
        cached_names = {c["factor_name"] for c in cached}
        computable = self.get_computable_factors()
        computable_names = {f["factor_name"] for f in computable}

        uncached = sorted(computable_names - cached_names)
        total_size_mb = sum(c.get("size_mb", 0) for c in cached)
        meta = self._load_meta()

        date_range = None
        for factor_meta in meta.get("factors", {}).values():
            if factor_meta.get("date_range"):
                date_range = factor_meta["date_range"]
                break

        return {
            "cached_count": len(cached),
            "total_computable": len(computable),
            "uncached_count": len(uncached),
            "uncached_factors": uncached[:50],
            "total_size_mb": round(total_size_mb, 1),
            "as_of_date": meta.get("as_of_date"),
            "generated_at": meta.get("generated_at"),
            "date_range": date_range,
        }
