from __future__ import annotations

from backend.services.strategy_package.runtime_variant import canonical_json_sha256

IDENTITY_COLUMNS = (
    "program_id",
    "binding_version_id",
    "package_id",
    "manifest_sha256",
    "decision_as_of_trade_date",
    "target_trade_date",
    "instrument",
    "selection_source_rank",
    "selection_effective_rank",
    "candidate_group_size",
    "selection_runtime_semantics_hash",
)

PARENT_FEATURE_COLUMNS = (
    "parent_combined_score",
    "parent_rank_pct",
    "lstm_raw_score",
    "lstm_norm_score",
    "lstm_leg_rank",
    "lstm_weight",
    "fund_raw_score",
    "fund_norm_score",
    "fund_leg_rank",
    "fund_weight",
    "leg_norm_score_gap",
    "leg_rank_gap",
    "leg_direction_agreement",
    "weight_concentration",
)

MARKET_FEATURE_COLUMNS = (
    "ret_1",
    "ret_3",
    "ret_5",
    "ret_10",
    "ret_20",
    "drawdown_20",
    "drawdown_60",
    "atr14_close",
    "intraday_range",
    "open_gap",
    "volume_ratio_5",
    "volume_ratio_20",
    "amount_ratio_5",
    "amount_ratio_20",
    "turnover_rate",
    "quoted_volume_ratio",
    "main_net_amt_ratio",
    "elg_net_amt_ratio",
    "main_net_amt_ratio_5",
    "main_net_amt_ratio_20",
    "elg_net_amt_ratio_5",
    "elg_net_amt_ratio_20",
    "value_pe_inv",
    "value_pb_inv",
    "size_log_mv",
    "revenue_yoy",
    "profit_yoy",
    "gross_margin",
    "net_margin",
    "chip_winner_rate",
    "chip_cost_spread",
    "chip_cost_position",
    "margin_balance_log",
    "margin_balance_change_5",
    "l2_code_id",
    "sector_ret_1",
    "sector_ret_5",
    "sector_ret_20",
    "sector_excess_5",
    "sector_excess_20",
    "sector_amount_ratio_20",
    "sector_net_amt_ratio",
    "csi300_ret_1",
    "csi300_ret_5",
    "csi300_ret_20",
    "market_up_ratio",
    "market_limit_up_ratio",
    "market_cross_section_vol",
    "hmm_bull_posterior",
    "hmm_state",
    "hmm_state_duration",
    "hmm_observation_completeness",
    "decision_is_suspended",
    "decision_limit_up",
    "decision_limit_down",
    "distance_to_limit_up",
    "distance_to_limit_down",
)

REQUIRED_FEATURE_COLUMNS = (
    *PARENT_FEATURE_COLUMNS,
    "ret_1",
    "ret_3",
    "ret_5",
    "ret_10",
    "ret_20",
    "drawdown_20",
    "drawdown_60",
    "atr14_close",
    "intraday_range",
    "open_gap",
    "volume_ratio_5",
    "volume_ratio_20",
    "amount_ratio_5",
    "amount_ratio_20",
    "csi300_ret_1",
    "csi300_ret_5",
    "csi300_ret_20",
    "market_up_ratio",
    "market_limit_up_ratio",
    "market_cross_section_vol",
    "decision_is_suspended",
    "decision_limit_up",
    "decision_limit_down",
    "distance_to_limit_up",
    "distance_to_limit_down",
)

OPTIONAL_FEATURE_COLUMNS = tuple(column for column in MARKET_FEATURE_COLUMNS if column not in REQUIRED_FEATURE_COLUMNS)
MISSING_INDICATOR_COLUMNS = tuple(f"{column}__missing" for column in OPTIONAL_FEATURE_COLUMNS)
MODEL_FEATURE_COLUMNS = (*PARENT_FEATURE_COLUMNS, *MARKET_FEATURE_COLUMNS, *MISSING_INDICATOR_COLUMNS)
CATEGORICAL_FEATURE_COLUMNS = ("l2_code_id",)

FEATURE_SCHEMA_PAYLOAD = {
    "schema_version": "advisory_feature_schema_v1",
    "identity_columns": IDENTITY_COLUMNS,
    "model_feature_columns": MODEL_FEATURE_COLUMNS,
    "required_feature_columns": REQUIRED_FEATURE_COLUMNS,
    "optional_feature_columns": OPTIONAL_FEATURE_COLUMNS,
    "categorical_feature_columns": CATEGORICAL_FEATURE_COLUMNS,
    "missing_indicator_columns": MISSING_INDICATOR_COLUMNS,
}
FEATURE_SCHEMA_HASH = canonical_json_sha256(FEATURE_SCHEMA_PAYLOAD)
