from __future__ import annotations

from typing import Any


class Phase0BAuditError(RuntimeError):
    """Stable visible failure for the read-only Phase 0B audit."""

    def __init__(
        self,
        reason_code: str,
        message: str,
        *,
        context: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.reason_code = reason_code
        self.context = dict(context or {})


REASON_CONFIG_MISSING = "ADVISORY_PHASE0B_CONFIG_MISSING"
REASON_TARGET_SET_CONFLICT = "ADVISORY_PHASE0B_TARGET_SET_CONFLICT"
REASON_WINNER_REGISTRY_CONFLICT = "ADVISORY_PHASE0B_WINNER_REGISTRY_CONFLICT"
REASON_STORE_IDENTITY_CONFLICT = "ADVISORY_PHASE0B_STORE_IDENTITY_CONFLICT"
REASON_SNAPSHOT_NOT_SEALED = "ADVISORY_PHASE0B_SNAPSHOT_NOT_SEALED"
REASON_SNAPSHOT_INVALIDATED = "ADVISORY_PHASE0B_SNAPSHOT_INVALIDATED"
REASON_SNAPSHOT_CHANGED = "ADVISORY_PHASE0B_SNAPSHOT_CHANGED_DURING_READ"
REASON_MANIFEST_CONFLICT = "ADVISORY_PHASE0B_MANIFEST_CONFLICT"
REASON_FILE_SET_CONFLICT = "ADVISORY_PHASE0B_FILE_SET_CONFLICT"
REASON_PARQUET_VERIFY_FAILED = "ADVISORY_PHASE0B_PARQUET_VERIFY_FAILED"
REASON_RELATION_CLOSURE_INVALID = "ADVISORY_PHASE0B_RELATION_CLOSURE_INVALID"
REASON_METRIC_REGISTRY_CONFLICT = "ADVISORY_PHASE0B_METRIC_REGISTRY_CONFLICT"
REASON_REPORT_BUNDLE_CONFLICT = "ADVISORY_PHASE0B_REPORT_BUNDLE_CONFLICT"

REASON_INSUFFICIENT_DECISION_DATES = "ADVISORY_PHASE0B_INSUFFICIENT_DECISION_DATES"
REASON_INSUFFICIENT_PAIRED_DECISION_DATES = (
    "ADVISORY_PHASE0B_INSUFFICIENT_PAIRED_DECISION_DATES"
)
REASON_INSUFFICIENT_MATURE_LABELS = "ADVISORY_PHASE0B_INSUFFICIENT_MATURE_LABELS"
REASON_INSUFFICIENT_WINNER_EVENTS = "ADVISORY_PHASE0B_INSUFFICIENT_WINNER_EVENTS"
REASON_REGIME_EVIDENCE_UNAVAILABLE = "ADVISORY_PHASE0B_REGIME_EVIDENCE_UNAVAILABLE"
REASON_UNIVERSE_OUTCOME_UNAVAILABLE = "ADVISORY_PHASE0B_UNIVERSE_OUTCOME_UNAVAILABLE"
REASON_BLACKLIST_COUNTERFACTUAL_UNAVAILABLE = (
    "ADVISORY_PHASE0B_BLACKLIST_COUNTERFACTUAL_UNAVAILABLE"
)
REASON_STAGE_CAPABILITY_UNAVAILABLE = "ADVISORY_PHASE0B_STAGE_CAPABILITY_UNAVAILABLE"
REASON_PROJECTION_NOT_APPLICABLE = "ADVISORY_PHASE0B_PROJECTION_NOT_APPLICABLE"
