"""StrategyPackage runtime and rebalance helpers.

Only package-based runtime artifacts are accepted. Single-alpha packages use
live QE inference artifacts; multi-alpha packages use authoritative combined
selection artifacts generated by the signal-layer provider.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import date
from typing import Any

from backend.execution_algos.board_lot import round_to_board_lot
from backend.services.selection_center.hmm_runtime import SectorHMMRuntime
from backend.services.selection_center.models import SelectionCandidate, SignalSnapshot, TargetPosition
from backend.services.selection_center.prospective_evidence import (
    HMMAdjustmentResult,
    REASON_VALID_NO_CANDIDATE_DECLARATION_FORBIDDEN,
    REASON_VALID_NO_CANDIDATE_EVIDENCE_INCOMPLETE,
)
from backend.services.selection_center.runtime_profile import normalize_selection_runtime_config, parse_selection_runtime_profile
from backend.services.strategy_package.backtest_contract import build_backtest_runtime_contract
from backend.services.strategy_package.manifest import freeze_manifest
from backend.services.strategy_package.models import AlphaMode, StrategyPackageManifest
from backend.services.strategy_package.runtime_variant import StrategyPackageRuntimeVariant
from backend.services.strategy_package.selection_artifact import (
    SELECTION_SCORE_ARTIFACT_CONTRACT_V2,
    StrategyPackageSelectionArtifactRepository,
    selection_artifact_runtime_hash,
    selection_artifact_runtime_hash_v2,
)
from backend.services.strategy_package.live_inference import (
    AUTHORITATIVE_SELECTION_SCOPE,
    AUTHORITATIVE_SELECTION_SOURCE_TYPE,
)
from backend.services.strategy_package.multi_alpha_live import (
    LIVE_MULTI_ALPHA_SELECTION_SOURCE_TYPE,
    REASON_PREDICTION_NOT_AUTHORITATIVE,
    REASON_RUNTIME_NOT_ENABLED,
    multi_alpha_selection_artifact_runtime_hash,
    multi_alpha_selection_artifact_runtime_hash_v2,
)
from backend.services.strategy_package.validators import StrategyPackageValidator
from backend.services.trading_core.errors import (
    ArtifactGenerationFailedError,
    DataUnavailableError,
    PackageAssetInvalidError,
    RuntimeConfigInvalidError,
    UnsupportedFeatureError,
)
from backend.services.trading_core.models import OrderIntent, OrderSide, PositionLot


SCORE_WEIGHTED_V2_LIKE_FAMILIES = {"score_weighted_topk_v2", "score_weighted_topk_v2_capacity_v1"}
_VARIANT_CONFIG_KEYS_FOR_SELECTION_ARTIFACT_HASH = {
    "portfolio_policy",
    "strategy_config",
    "execution_policy",
    "minute_execution_policy",
}


@dataclass(frozen=True)
class SignalSnapshotBuildTrace:
    """The one-pass signal objects used by selection and prospective evidence."""

    snapshot: SignalSnapshot
    score_artifact: Any
    alpha_raw_candidates: list[SelectionCandidate]
    hmm_result: HMMAdjustmentResult


def apply_runtime_variant_config(
    runtime_config: dict[str, Any],
    variant: StrategyPackageRuntimeVariant | None,
) -> dict[str, Any]:
    """Attach an audited StrategyPackage runtime variant to runtime config."""

    if variant is None:
        return dict(runtime_config or {})
    config = dict(runtime_config or {})
    if config.get("runtime_variant"):
        raise RuntimeConfigInvalidError(
            "runtime_config already contains runtime_variant metadata",
            context={"runtime_variant_id": variant.variant_id},
        )
    for key in _VARIANT_CONFIG_KEYS_FOR_SELECTION_ARTIFACT_HASH:
        if key in variant.variant_config:
            config[key] = variant.variant_config[key]
    config["runtime_variant"] = {
        "variant_id": variant.variant_id,
        "variant_hash": variant.variant_hash,
        "variant_kind": variant.variant_kind.value,
        "variant_name": variant.variant_name,
        "manifest_sha256": variant.manifest_sha256,
        "locked_core_hash": variant.locked_core_hash,
        "variant_config": variant.variant_config,
        "validation_status": variant.validation_status.value,
        "paper_candidate": variant.paper_candidate,
    }
    return config


def apply_runtime_variant_to_manifest(
    manifest: StrategyPackageManifest,
    runtime_config: dict[str, Any] | None,
) -> StrategyPackageManifest:
    """Materialize non-core variant strategy settings for runtime decisions."""

    variant = (runtime_config or {}).get("runtime_variant")
    if not isinstance(variant, dict):
        return manifest
    variant_config = variant.get("variant_config")
    if not isinstance(variant_config, dict) or not variant_config:
        return manifest
    updates: dict[str, Any] = {}
    for key in ("strategy_config", "portfolio_policy"):
        if key in variant_config:
            updates[key] = _merge_model_or_dict(getattr(manifest, key), variant_config[key])
    if not updates:
        return manifest
    return freeze_manifest(manifest.model_copy(update=updates))


class StrategyPackageRuntime:
    """Load package runtime scores into a strict signal snapshot."""

    def __init__(
        self,
        validator: StrategyPackageValidator | None = None,
        hmm_runtime: SectorHMMRuntime | None = None,
        artifact_repository: StrategyPackageSelectionArtifactRepository | None = None,
    ) -> None:
        self.validator = validator or StrategyPackageValidator()
        self.hmm_runtime = hmm_runtime or SectorHMMRuntime()
        self.artifact_repository = artifact_repository or StrategyPackageSelectionArtifactRepository()

    def build_signal_snapshot(
        self,
        *,
        manifest: StrategyPackageManifest,
        trade_date: date,
        data_source: str,
        runtime_config: dict[str, Any] | None = None,
    ) -> SignalSnapshot:
        return self.build_signal_snapshot_with_trace(
            manifest=manifest,
            trade_date=trade_date,
            data_source=data_source,
            runtime_config=runtime_config,
        ).snapshot

    def build_signal_snapshot_with_trace(
        self,
        *,
        manifest: StrategyPackageManifest,
        trade_date: date,
        data_source: str,
        runtime_config: dict[str, Any] | None = None,
        require_frozen_hmm_snapshot: bool = False,
        hmm_effective_trade_date: date | None = None,
        prohibit_no_candidate_declaration: bool = False,
    ) -> SignalSnapshotBuildTrace:
        self.validator.validate_manifest(manifest)
        if not manifest.manifest_sha256:
            raise PackageAssetInvalidError(
                "strategy package manifest must be frozen before runtime",
                context={"package_id": manifest.package_id},
            )
        config = normalize_selection_runtime_config(runtime_config or {})
        if prohibit_no_candidate_declaration and any(
            key in config for key in ("valid_no_candidate", "no_candidate_reason")
        ):
            raise RuntimeConfigInvalidError(
                "prospective selection cannot declare valid_no_candidate in runtime_config",
                context={
                    "reason_code": REASON_VALID_NO_CANDIDATE_DECLARATION_FORBIDDEN,
                    "package_id": manifest.package_id,
                    "declared_keys": [
                        key for key in ("valid_no_candidate", "no_candidate_reason") if key in config
                    ],
                },
            )
        if manifest.alpha_mode == AlphaMode.MULTI_ALPHA:
            if not self._has_multi_alpha_runtime(manifest, config):
                raise UnsupportedFeatureError(
                    "multi_alpha runtime provider is not enabled",
                    context={"reason_code": REASON_RUNTIME_NOT_ENABLED, "package_id": manifest.package_id},
                )
        score_artifact, rows = self._load_score_artifact_rows(
            manifest,
            config,
            trade_date=trade_date,
            data_source=data_source,
        )
        runtime_profile = parse_selection_runtime_profile(config)
        if not rows:
            if self._is_natural_raw_empty_artifact(score_artifact):
                hmm_result = self.hmm_runtime.adjust_candidates_with_receipt(
                    candidates=[],
                    trade_date=trade_date,
                    profile=runtime_profile.hmm,
                    package_id=manifest.package_id,
                    manifest_sha256=manifest.manifest_sha256,
                    require_frozen_snapshot=require_frozen_hmm_snapshot,
                    effective_trade_date=hmm_effective_trade_date,
                )
                snapshot = SignalSnapshot(
                    package_id=manifest.package_id,
                    manifest_sha256=manifest.manifest_sha256,
                    trade_date=trade_date,
                    data_source=data_source,
                    candidates=[],
                    runtime_config=config,
                    valid_no_candidate=True,
                    no_candidate_reason="authoritative raw artifact produced no candidates",
                )
                return SignalSnapshotBuildTrace(
                    snapshot=snapshot,
                    score_artifact=score_artifact,
                    alpha_raw_candidates=[],
                    hmm_result=hmm_result,
                )
            if self._legacy_no_candidate_declaration_is_allowed(config, prospective=prohibit_no_candidate_declaration):
                hmm_result = self.hmm_runtime.adjust_candidates_with_receipt(
                    candidates=[],
                    trade_date=trade_date,
                    profile=runtime_profile.hmm,
                    package_id=manifest.package_id,
                    manifest_sha256=manifest.manifest_sha256,
                    require_frozen_snapshot=require_frozen_hmm_snapshot,
                    effective_trade_date=hmm_effective_trade_date,
                )
                snapshot = SignalSnapshot(
                    package_id=manifest.package_id,
                    manifest_sha256=manifest.manifest_sha256,
                    trade_date=trade_date,
                    data_source=data_source,
                    candidates=[],
                    runtime_config=config,
                    valid_no_candidate=True,
                    no_candidate_reason=str(config.get("no_candidate_reason") or "preview/replay declared no candidate"),
                )
                return SignalSnapshotBuildTrace(
                    snapshot=snapshot,
                    score_artifact=score_artifact,
                    alpha_raw_candidates=[],
                    hmm_result=hmm_result,
                )
            raise DataUnavailableError(
                "selection runtime produced no candidates without a valid raw-empty artifact receipt",
                context={
                    "package_id": manifest.package_id,
                    "trade_date": trade_date.isoformat(),
                    "reason_code": REASON_VALID_NO_CANDIDATE_EVIDENCE_INCOMPLETE,
                    "artifact_id": getattr(score_artifact, "artifact_id", None),
                },
            )
        alpha_raw_candidates = [self._candidate_from_row(row, manifest.package_id) for row in rows]
        alpha_raw_candidates.sort(key=lambda item: item.rank)
        hmm_result = self.hmm_runtime.adjust_candidates_with_receipt(
            candidates=alpha_raw_candidates,
            trade_date=trade_date,
            profile=runtime_profile.hmm,
            package_id=manifest.package_id,
            manifest_sha256=manifest.manifest_sha256,
            require_frozen_snapshot=require_frozen_hmm_snapshot,
            effective_trade_date=hmm_effective_trade_date,
        )
        snapshot = SignalSnapshot(
            package_id=manifest.package_id,
            manifest_sha256=manifest.manifest_sha256,
            trade_date=trade_date,
            data_source=data_source,
            candidates=hmm_result.candidates,
            runtime_config=config,
        )
        return SignalSnapshotBuildTrace(
            snapshot=snapshot,
            score_artifact=score_artifact,
            alpha_raw_candidates=alpha_raw_candidates,
            hmm_result=hmm_result,
        )

    def _load_score_rows(
        self,
        manifest: StrategyPackageManifest,
        config: dict[str, Any],
        *,
        trade_date: date,
        data_source: str,
    ) -> list[dict[str, Any]]:
        _, rows = self._load_score_artifact_rows(
            manifest,
            config,
            trade_date=trade_date,
            data_source=data_source,
        )
        return rows

    def _load_score_artifact_rows(
        self,
        manifest: StrategyPackageManifest,
        config: dict[str, Any],
        *,
        trade_date: date,
        data_source: str,
    ) -> tuple[Any, list[dict[str, Any]]]:
        if "selection_scores" in config:
            raise RuntimeConfigInvalidError(
                "runtime_config.selection_scores cannot be used as StrategyPackage signal input; "
                "generate an authoritative live selection artifact first",
                context={"package_id": manifest.package_id, "trade_date": trade_date.isoformat()},
            )
        selection_runtime = _selection_runtime_evidence(manifest)
        legacy_runtime_hashes = _candidate_selection_artifact_runtime_hashes(config)
        v2_runtime_hashes = _candidate_selection_artifact_runtime_hashes_v2(config)
        if manifest.alpha_mode == AlphaMode.MULTI_ALPHA:
            multi_v2_hash = multi_alpha_selection_artifact_runtime_hash_v2(manifest, config)
            multi_hash = multi_alpha_selection_artifact_runtime_hash(manifest, config)
            v2_runtime_hashes = [multi_v2_hash, *[item for item in v2_runtime_hashes if item != multi_v2_hash]]
            legacy_runtime_hashes = [multi_hash, *[item for item in legacy_runtime_hashes if item != multi_hash]]
        # New authoritative artifacts use v2. Legacy rows remain readable only
        # for existing operational records and can never become prospective DSE.
        runtime_hashes = [*v2_runtime_hashes, *[item for item in legacy_runtime_hashes if item not in v2_runtime_hashes]]
        artifact_error: DataUnavailableError | None = None
        artifact = None
        for runtime_hash in runtime_hashes:
            try:
                artifact = self.artifact_repository.get(
                    package_id=manifest.package_id,
                    manifest_sha256=manifest.manifest_sha256 or "",
                    trade_date=trade_date,
                    data_source=data_source,
                    runtime_config_hash=runtime_hash,
                )
                break
            except DataUnavailableError as exc:
                artifact_error = exc
        if artifact is not None:
            if artifact.status.value != "SUCCEEDED":
                raise DataUnavailableError(
                    "selection score artifact is not succeeded",
                    context={
                        "package_id": manifest.package_id,
                        "artifact_id": artifact.artifact_id,
                        "status": artifact.status.value,
                        "error_json": artifact.error_json,
                    },
                )
            self._require_authoritative_artifact(artifact, config, manifest=manifest)
            if not artifact.scores_json and not self._is_natural_raw_empty_artifact(artifact):
                raise DataUnavailableError(
                    "selection score artifact contains no scores",
                    context={
                        "package_id": manifest.package_id,
                        "artifact_id": artifact.artifact_id,
                        "reason_code": REASON_VALID_NO_CANDIDATE_EVIDENCE_INCOMPLETE,
                    },
                )
            return artifact, artifact.scores_json

        if "scores" in selection_runtime:
            raise RuntimeConfigInvalidError(
                "manifest strategy_config.selection_runtime.scores is not authoritative; "
                "StrategyPackage runtime must use live/latest-data inference artifacts",
                context={"package_id": manifest.package_id, "trade_date": trade_date.isoformat()},
            )
        scores_path = selection_runtime.get("scores_path")
        if scores_path:
            raise RuntimeConfigInvalidError(
                "manifest strategy_config.selection_runtime.scores_path is not authoritative; "
                "StrategyPackage runtime must use live/latest-data inference artifacts",
                context={
                    "package_id": manifest.package_id,
                    "trade_date": trade_date.isoformat(),
                    "scores_path": str(scores_path),
                },
            )
        if artifact_error is not None:
            raise artifact_error
        raise DataUnavailableError(
            "selection score artifact is missing; generate selection artifact first",
            context={"package_id": manifest.package_id, "trade_date": trade_date.isoformat()},
        )

    def _require_authoritative_artifact(
        self,
        artifact: Any,
        config: dict[str, Any],
        *,
        manifest: StrategyPackageManifest,
    ) -> None:
        metadata = artifact.metadata or {}
        source_type = metadata.get("source_type")
        authority_scope = metadata.get("authority_scope")
        required_source_type = (
            LIVE_MULTI_ALPHA_SELECTION_SOURCE_TYPE
            if manifest.alpha_mode == AlphaMode.MULTI_ALPHA
            else AUTHORITATIVE_SELECTION_SOURCE_TYPE
        )
        if source_type == required_source_type and authority_scope == AUTHORITATIVE_SELECTION_SCOPE:
            if manifest.alpha_mode == AlphaMode.MULTI_ALPHA and metadata.get("authority_scope") != AUTHORITATIVE_SELECTION_SCOPE:
                raise AssertionError("unreachable")
            return
        context = {
            "package_id": artifact.package_id,
            "artifact_id": artifact.artifact_id,
            "trade_date": artifact.trade_date.isoformat(),
            "data_source": artifact.data_source,
            "source_type": source_type,
            "authority_scope": authority_scope,
            "required_source_type": required_source_type,
            "required_authority_scope": AUTHORITATIVE_SELECTION_SCOPE,
        }
        if manifest.alpha_mode == AlphaMode.MULTI_ALPHA:
            context["reason_code"] = REASON_PREDICTION_NOT_AUTHORITATIVE
        raise DataUnavailableError(
            "selection score artifact is not authoritative live inference output",
            context=context,
        )

    @staticmethod
    def _is_natural_raw_empty_artifact(artifact: Any) -> bool:
        """Recognize only the v2 state machine's proof-backed raw-empty state."""

        metadata = getattr(artifact, "metadata", None) or {}
        try:
            score_count = int(getattr(artifact, "score_count", -1))
            universe_count = int(getattr(artifact, "universe_count", 0))
        except (TypeError, ValueError):
            return False
        return (
            getattr(artifact, "artifact_contract_version", None) == SELECTION_SCORE_ARTIFACT_CONTRACT_V2
            and getattr(getattr(artifact, "status", None), "value", None) == "SUCCEEDED"
            and not getattr(artifact, "scores_json", None)
            and score_count == 0
            and universe_count > 0
            and metadata.get("candidate_outcome") == "VALID_NO_CANDIDATE"
            and metadata.get("empty_stage") == "alpha_raw"
            and getattr(artifact, "top_score_symbol", None) is None
        )

    @staticmethod
    def _legacy_no_candidate_declaration_is_allowed(config: dict[str, Any], *, prospective: bool) -> bool:
        """Retain the legacy diagnostic escape hatch without making it formal evidence."""

        if prospective or not bool(config.get("valid_no_candidate")):
            return False
        artifact_config = config.get("selection_artifact_config") or config.get("selection_artifact") or {}
        if not isinstance(artifact_config, dict):
            return False
        return (
            str(artifact_config.get("execution_origin") or "").strip().upper() in {"PREVIEW", "REPLAY"}
            and bool(str(artifact_config.get("diagnostic_run_id") or "").strip())
        )

    def _candidate_from_row(self, row: dict[str, Any], package_id: str) -> SelectionCandidate:
        missing = [key for key in ("symbol", "score", "rank") if row.get(key) is None]
        if missing:
            raise ArtifactGenerationFailedError(
                "selection candidate is missing required score fields",
                context={"package_id": package_id, "missing": missing, "row": row},
            )
        return SelectionCandidate(
            symbol=str(row["symbol"]),
            score=float(row["score"]),
            rank=int(row["rank"]),
            target_weight=float(row["target_weight"]) if row.get("target_weight") is not None else None,
            target_quantity=int(row["target_quantity"]) if row.get("target_quantity") is not None else None,
            reference_price=float(row["reference_price"]) if row.get("reference_price") is not None else None,
            component_scores=row.get("component_scores") or {},
            reason=row.get("reason"),
        )

    @staticmethod
    def _has_multi_alpha_runtime(manifest: StrategyPackageManifest, config: dict[str, Any]) -> bool:
        artifact_config = config.get("selection_artifact_config") or config.get("selection_artifact") or {}
        if artifact_config and not isinstance(artifact_config, dict):
            raise RuntimeConfigInvalidError("selection_artifact_config must be an object")
        return bool((artifact_config or {}).get("multi_alpha_live_inference_enabled", True))


def _selection_runtime_evidence(manifest: StrategyPackageManifest) -> dict[str, Any]:
    source_evidence = manifest.source_evidence or {}
    selection_runtime = source_evidence.get("selection_runtime")
    if isinstance(selection_runtime, dict):
        return selection_runtime
    if manifest.is_legacy_runtime_manifest:
        strategy_config = manifest.strategy_config or {}
        legacy_runtime = strategy_config.get("selection_runtime") if isinstance(strategy_config, dict) else None
        if isinstance(legacy_runtime, dict):
            return legacy_runtime
    return {}


class TargetPositionEngine:
    """Convert selection candidates into target positions."""

    def build_targets(
        self,
        *,
        snapshot: SignalSnapshot,
        total_equity: float,
        top_k: int,
        manifest: StrategyPackageManifest | None = None,
        current_positions: dict[str, PositionLot] | None = None,
        current_prices: dict[str, float] | None = None,
        default_target_weight: float | None = None,
    ) -> list[TargetPosition]:
        if snapshot.valid_no_candidate:
            raise DataUnavailableError(
                "valid_no_candidate snapshots cannot produce target positions",
                context={"package_id": snapshot.package_id, "reason": snapshot.no_candidate_reason},
            )
        if total_equity <= 0:
            raise RuntimeConfigInvalidError("total_equity must be positive for target positions")
        if top_k <= 0:
            raise RuntimeConfigInvalidError("top_k must be positive for target positions")
        if manifest is not None:
            return self._build_targets_from_backtest_contract(
                snapshot=snapshot,
                total_equity=total_equity,
                manifest=manifest,
                current_positions=current_positions or {},
                current_prices=current_prices or {},
            )
        selected = sorted(snapshot.candidates, key=lambda item: item.rank)[:top_k]
        if not selected:
            raise ArtifactGenerationFailedError("target position engine received no candidates")
        targets: list[TargetPosition] = []
        for candidate in selected:
            if candidate.target_quantity is not None:
                if candidate.target_quantity < 0:
                    raise ArtifactGenerationFailedError(
                        "candidate target_quantity must be non-negative",
                        context={"package_id": snapshot.package_id, "symbol": candidate.symbol},
                    )
                if candidate.target_quantity > 0 and candidate.reference_price is None:
                    raise DataUnavailableError(
                        "target_quantity requires reference_price for traceability",
                        context={"package_id": snapshot.package_id, "symbol": candidate.symbol},
                    )
                quantity = candidate.target_quantity
                target_weight = candidate.target_weight if quantity > 0 else None
            else:
                if candidate.target_weight is None:
                    if default_target_weight is None:
                        raise ArtifactGenerationFailedError(
                            "candidate is missing target position information",
                            context={"package_id": snapshot.package_id, "symbol": candidate.symbol},
                        )
                    candidate_weight = default_target_weight
                else:
                    candidate_weight = candidate.target_weight
                if candidate.reference_price is None:
                    raise DataUnavailableError(
                        "candidate reference_price is required to compute target quantity",
                        context={"package_id": snapshot.package_id, "symbol": candidate.symbol},
                    )
                raw_quantity = int(total_equity * candidate_weight / candidate.reference_price)
                quantity = round_to_board_lot(raw_quantity, candidate.symbol, side="BUY")
                target_weight = candidate_weight
            if quantity <= 0 and candidate.target_quantity is None:
                raise ArtifactGenerationFailedError(
                    "target position rounds to zero shares",
                    context={"package_id": snapshot.package_id, "symbol": candidate.symbol},
                )
            targets.append(
                TargetPosition(
                    symbol=candidate.symbol,
                    target_quantity=quantity,
                    target_weight=target_weight,
                    reference_price=candidate.reference_price,
                    score=candidate.score,
                    rank=candidate.rank,
                    reason=candidate.reason or "selection_target",
                    metadata={"snapshot_id": snapshot.snapshot_id, "component_scores": candidate.component_scores},
                )
            )
        return targets

    def _build_targets_from_backtest_contract(
        self,
        *,
        snapshot: SignalSnapshot,
        total_equity: float,
        manifest: StrategyPackageManifest,
        current_positions: dict[str, PositionLot],
        current_prices: dict[str, float],
    ) -> list[TargetPosition]:
        contract = build_backtest_runtime_contract(manifest)
        strategy = contract["portfolio_strategy"]
        family = strategy["strategy_family"]
        if family not in {"score_weighted_topk_v1", *SCORE_WEIGHTED_V2_LIKE_FAMILIES}:
            raise UnsupportedFeatureError(
                "Paper v2 does not support the QE portfolio strategy contract yet",
                context={"package_id": manifest.package_id, "strategy_family": family},
            )
        return self._build_score_weighted_targets(
            snapshot=snapshot,
            total_equity=total_equity,
            current_positions=current_positions,
            current_prices=current_prices,
            params=strategy["params"],
            strategy_family=family,
        )

    def _build_score_weighted_targets(
        self,
        *,
        snapshot: SignalSnapshot,
        total_equity: float,
        current_positions: dict[str, PositionLot],
        current_prices: dict[str, float],
        params: dict[str, Any],
        strategy_family: str,
    ) -> list[TargetPosition]:
        ordered = sorted(snapshot.candidates, key=lambda item: (item.rank, -item.score, item.symbol))
        if not ordered:
            raise ArtifactGenerationFailedError("target position engine received no candidates")

        topk = int(params["topk"])
        max_n_drop = int(params["max_n_drop"])
        topk_candidates = ordered[:topk]
        topk_symbols = {candidate.symbol for candidate in topk_candidates}
        score_by_symbol = {candidate.symbol: float(candidate.score) for candidate in ordered}
        candidate_by_symbol = {candidate.symbol: candidate for candidate in ordered}
        current_symbols = list(current_positions)
        valid_holdings = [symbol for symbol in current_symbols if symbol in score_by_symbol]

        sell_candidates = [
            (symbol, float(score_by_symbol.get(symbol, -999.0)))
            for symbol in valid_holdings
            if symbol not in topk_symbols
        ]
        sell_candidates.sort(key=lambda item: (item[1], item[0]))
        buy_candidates = [
            (candidate.symbol, float(candidate.score))
            for candidate in topk_candidates
            if candidate.symbol not in current_positions
        ]
        buy_candidates.sort(key=lambda item: (-item[1], item[0]))

        ghost_sells: list[str] = []
        is_v2_like = strategy_family in SCORE_WEIGHTED_V2_LIKE_FAMILIES
        if is_v2_like:
            ghost_sells = [symbol for symbol in current_symbols if symbol not in score_by_symbol]

        if (len(valid_holdings) if is_v2_like else len(current_symbols)) < topk:
            if is_v2_like:
                actual_sells = [symbol for symbol, _ in sell_candidates[:max_n_drop]]
                remaining_after_sell = len(valid_holdings) - len(actual_sells)
                buy_slots = max(0, topk - remaining_after_sell)
                actual_buys = [symbol for symbol, _ in buy_candidates[:buy_slots]]
            else:
                actual_sells = []
                slots = max(0, topk - len(current_symbols))
                actual_buys = [symbol for symbol, _ in buy_candidates[:slots]]
        else:
            actual_sells, actual_buys = self._filter_dynamic_ndrop(
                sell_candidates=sell_candidates,
                buy_candidates=buy_candidates,
                current_scores=[score_by_symbol[symbol] for symbol in valid_holdings],
                params=params,
            )

        requested_sells = list(actual_sells) + ghost_sells
        all_sells = [
            symbol
            for symbol in requested_sells
            if self._can_sell_under_hold_thresh(symbol, current_positions, snapshot.trade_date, params)
        ]
        retained_symbols = [symbol for symbol in current_symbols if symbol not in set(all_sells)]
        max_buy_slots = max(0, topk - len(retained_symbols))
        if len(actual_buys) > max_buy_slots:
            actual_buys = actual_buys[:max_buy_slots]

        final_symbols = [*retained_symbols, *actual_buys]
        scored_final_symbols = [symbol for symbol in final_symbols if symbol in score_by_symbol]
        weights = self._compute_score_weighted_weights(
            [score_by_symbol[symbol] for symbol in scored_final_symbols],
            params=params,
        )
        weight_by_symbol = {
            symbol: float(weights[idx])
            for idx, symbol in enumerate(scored_final_symbols)
            if idx < len(weights)
        }

        targets: list[TargetPosition] = []
        for symbol in all_sells:
            candidate = candidate_by_symbol.get(symbol)
            targets.append(
                TargetPosition(
                    symbol=symbol,
                    target_quantity=0,
                    target_weight=None,
                    reference_price=self._optional_current_reference_price(symbol, current_prices),
                    score=score_by_symbol.get(symbol, 0.0),
                    rank=candidate.rank if candidate is not None else 999999,
                    reason="qe_backtest_score_weighted_ghost_sell"
                    if symbol in ghost_sells
                    else "qe_backtest_score_weighted_sell",
                    metadata={
                        "snapshot_id": snapshot.snapshot_id,
                        "qe_strategy_family": strategy_family,
                        "component_scores": candidate.component_scores if candidate is not None else {},
                        "current_quantity_before_sell": current_positions[symbol].quantity
                        if symbol in current_positions
                        else 0,
                    },
                )
            )
        for symbol in final_symbols:
            candidate = candidate_by_symbol.get(symbol)
            existing = current_positions.get(symbol)
            weight = weight_by_symbol.get(symbol)
            if existing is not None and symbol not in actual_buys:
                quantity = existing.quantity
                reference_price = candidate.reference_price if candidate is not None else None
                if reference_price is None and quantity > 0:
                    reference_price = self._required_current_reference_price(
                        symbol,
                        current_prices,
                        context={"package_id": snapshot.package_id, "reason": "retain_existing_position"},
                    )
                targets.append(
                    TargetPosition(
                        symbol=symbol,
                        target_quantity=quantity,
                        target_weight=weight,
                        reference_price=reference_price,
                        score=score_by_symbol.get(symbol, 0.0),
                        rank=candidate.rank if candidate is not None else 999999,
                        reason="qe_backtest_score_weighted_retain",
                        metadata={
                            "snapshot_id": snapshot.snapshot_id,
                            "qe_strategy_family": strategy_family,
                            "component_scores": candidate.component_scores if candidate is not None else {},
                            "current_quantity_retained": quantity,
                        },
                    )
                )
                continue
            if symbol not in actual_buys:
                continue
            if candidate is None or candidate.reference_price is None:
                raise DataUnavailableError(
                    "QE score-weighted target requires reference_price for buy candidate",
                    context={"package_id": snapshot.package_id, "symbol": symbol},
                )
            if not weight or weight <= 0:
                continue
            target_value = min(total_equity * weight, float(params["max_single_order_value"]))
            raw_quantity = int(target_value / candidate.reference_price)
            quantity = round_to_board_lot(raw_quantity, symbol, side="BUY")
            if quantity <= 0:
                continue
            targets.append(
                TargetPosition(
                    symbol=symbol,
                    target_quantity=quantity,
                    target_weight=weight,
                    reference_price=candidate.reference_price,
                    score=candidate.score,
                    rank=candidate.rank,
                    reason="qe_backtest_score_weighted_buy",
                    metadata={
                        "snapshot_id": snapshot.snapshot_id,
                        "qe_strategy_family": strategy_family,
                        "component_scores": candidate.component_scores,
                        "target_value": target_value,
                    },
                )
            )
        if not targets and current_positions:
            return [
                TargetPosition(
                    symbol=symbol,
                    target_quantity=position.quantity,
                    target_weight=None,
                    reference_price=self._required_current_reference_price(
                        symbol,
                        current_prices,
                        context={"package_id": snapshot.package_id, "reason": "score_weighted_no_change"},
                    ),
                    score=0.0,
                    rank=999999,
                    reason="qe_backtest_score_weighted_no_change",
                    metadata={"snapshot_id": snapshot.snapshot_id, "qe_strategy_family": strategy_family},
                )
                for symbol, position in sorted(current_positions.items())
            ]
        if not targets:
            raise ArtifactGenerationFailedError(
                "QE score-weighted strategy produced no target positions",
                context={"package_id": snapshot.package_id, "candidate_count": len(snapshot.candidates)},
            )
        return targets

    @staticmethod
    def _optional_current_reference_price(symbol: str, current_prices: dict[str, float]) -> float | None:
        price = current_prices.get(symbol)
        if price is None:
            return None
        value = float(price)
        if value <= 0 or not math.isfinite(value):
            return None
        return value

    @staticmethod
    def _required_current_reference_price(
        symbol: str,
        current_prices: dict[str, float],
        *,
        context: dict[str, Any],
    ) -> float:
        price = current_prices.get(symbol)
        if price is None:
            raise DataUnavailableError(
                "current price is required for retained QE target position",
                context={**context, "symbol": symbol},
            )
        value = float(price)
        if value <= 0 or not math.isfinite(value):
            raise DataUnavailableError(
                "current price for retained QE target position must be positive",
                context={**context, "symbol": symbol, "current_price": price},
            )
        return value

    def _filter_dynamic_ndrop(
        self,
        *,
        sell_candidates: list[tuple[str, float]],
        buy_candidates: list[tuple[str, float]],
        current_scores: list[float],
        params: dict[str, Any],
    ) -> tuple[list[str], list[str]]:
        max_n_drop = int(params["max_n_drop"])
        min_n_drop = int(params["min_n_drop"])
        if not bool(params.get("enable_dynamic_ndrop", True)):
            n = min(max_n_drop, len(sell_candidates), len(buy_candidates))
            return [s for s, _ in sell_candidates[:n]], [b for b, _ in buy_candidates[:n]]
        sell_cands = sell_candidates[:max_n_drop]
        buy_cands = buy_candidates[:max_n_drop]
        threshold = self._compute_threshold(current_scores, params)
        actual_sells: list[str] = []
        actual_buys: list[str] = []
        for idx in range(min(len(sell_cands), len(buy_cands))):
            sell_symbol, sell_score = sell_cands[idx]
            buy_symbol, buy_score = buy_cands[idx]
            if buy_score - sell_score > threshold:
                actual_sells.append(sell_symbol)
                actual_buys.append(buy_symbol)
            else:
                break
        while len(actual_sells) < min_n_drop:
            idx = len(actual_sells)
            if idx < len(sell_cands) and idx < len(buy_cands):
                actual_sells.append(sell_cands[idx][0])
                actual_buys.append(buy_cands[idx][0])
            else:
                break
        return actual_sells, actual_buys

    @staticmethod
    def _compute_threshold(current_scores: list[float], params: dict[str, Any]) -> float:
        if not current_scores:
            return float(params.get("threshold_floor") or 0.0)
        values = sorted(float(item) for item in current_scores if math.isfinite(float(item)))
        if not values:
            return float(params.get("threshold_floor") or 0.0)
        method = str(params.get("threshold_method") or "adaptive")
        floor = float(params.get("threshold_floor") or 0.0)
        if method == "fixed":
            return max(float(params.get("min_improvement") or 0.0), floor)
        spread = max(values) - min(values)
        if method == "percentile":
            return max(spread * float(params.get("min_improvement") or 0.0), floor)
        return max(spread * float(params.get("adaptive_multiplier") or 0.0), floor)

    @staticmethod
    def _compute_score_weighted_weights(scores: list[float], *, params: dict[str, Any]) -> list[float]:
        if not scores:
            return []
        values = [float(score) for score in scores]
        method = str(params.get("weight_method") or "softmax")
        if method == "equal":
            weights = [1.0 / len(values)] * len(values)
        elif method == "rank":
            ranked = sorted(range(len(values)), key=lambda idx: values[idx])
            ranks = [0.0] * len(values)
            for rank, idx in enumerate(ranked, start=1):
                ranks[idx] = float(rank)
            total = sum(ranks) or 1.0
            weights = [rank / total for rank in ranks]
        elif method == "linear":
            minimum = min(values)
            shifted = [value - minimum + 1e-8 for value in values]
            total = sum(shifted) or 1.0
            weights = [value / total for value in shifted]
        elif method == "softmax":
            temperature = max(float(params.get("temperature") or 1.0), 0.01)
            scaled = [value / temperature for value in values]
            maximum = max(scaled)
            exp_values = [math.exp(value - maximum) for value in scaled]
            total = sum(exp_values) or 1.0
            weights = [value / total for value in exp_values]
        else:
            raise RuntimeConfigInvalidError(
                "unsupported QE score-weighted weight_method",
                context={"weight_method": method},
            )

        min_weight = float(params.get("min_weight") or 0.0)
        max_weight = float(params.get("max_weight") or 1.0)
        for _ in range(10):
            over = [idx for idx, value in enumerate(weights) if value > max_weight]
            under = [idx for idx, value in enumerate(weights) if 0 < value < min_weight]
            if not over and not under:
                break
            if over:
                excess = sum(weights[idx] - max_weight for idx in over)
                for idx in over:
                    weights[idx] = max_weight
                free = [idx for idx in range(len(weights)) if idx not in over]
                free_total = sum(weights[idx] for idx in free)
                if free and free_total > 0:
                    for idx in free:
                        weights[idx] += excess * weights[idx] / free_total
            if under:
                deficit = sum(min_weight - weights[idx] for idx in under)
                for idx in under:
                    weights[idx] = min_weight
                free = [idx for idx in range(len(weights)) if idx not in over and idx not in under]
                free_total = sum(weights[idx] for idx in free)
                if free and free_total > 0:
                    for idx in free:
                        weights[idx] = max(weights[idx] - deficit * weights[idx] / free_total, min_weight)
        total = sum(weights)
        if total > 0:
            ratio = float(params.get("max_position_ratio") or 1.0)
            weights = [weight / total * ratio for weight in weights]
        return weights

    @staticmethod
    def _can_sell_under_hold_thresh(
        symbol: str,
        current_positions: dict[str, PositionLot],
        trade_date: date,
        params: dict[str, Any],
    ) -> bool:
        hold_thresh = float(params.get("hold_thresh") or 0)
        if hold_thresh <= 0:
            return True
        position = current_positions.get(symbol)
        if position is None:
            return True
        return float((trade_date - position.trade_date).days) >= hold_thresh


class RebalanceEngine:
    """Diff current positions and target positions into OrderIntent objects."""

    def build_order_intents(
        self,
        *,
        package_id: str,
        portfolio_id: str,
        trade_date: date,
        current_positions: dict[str, PositionLot],
        target_positions: list[TargetPosition],
    ) -> list[OrderIntent]:
        if not target_positions:
            raise ArtifactGenerationFailedError(
                "rebalance requires target positions",
                context={"package_id": package_id, "portfolio_id": portfolio_id},
            )
        target_by_symbol = {target.symbol: target for target in target_positions}
        symbols = sorted(set(current_positions) | set(target_by_symbol))
        intents: list[OrderIntent] = []
        for symbol in symbols:
            current_qty = current_positions.get(symbol).quantity if symbol in current_positions else 0
            target_qty = target_by_symbol[symbol].target_quantity if symbol in target_by_symbol else 0
            delta = target_qty - current_qty
            if delta == 0:
                continue
            side = OrderSide.BUY if delta > 0 else OrderSide.SELL
            requested_quantity = abs(delta)
            quantity = round_to_board_lot(requested_quantity, symbol, side=side.value)
            if quantity <= 0:
                continue
            rebalance_reason = (
                target_by_symbol[symbol].reason if symbol in target_by_symbol else "DROPPED_FROM_SELECTION"
            )
            metadata = {
                "target_quantity": target_qty,
                "current_quantity": current_qty,
                "target_weight": target_by_symbol[symbol].target_weight if symbol in target_by_symbol else None,
                "requested_quantity": requested_quantity,
                "rebalance_reason": rebalance_reason,
                "target_metadata": target_by_symbol[symbol].metadata
                if symbol in target_by_symbol
                else {},
            }
            if quantity < requested_quantity:
                metadata.update(
                    {
                        "emitted_quantity": quantity,
                        "residual_quantity": requested_quantity - quantity,
                    }
                )
            intents.append(
                OrderIntent(
                    package_id=package_id,
                    portfolio_id=portfolio_id,
                    symbol=symbol,
                    side=side,
                    quantity=quantity,
                    target_trade_date=trade_date,
                    metadata=metadata,
                )
            )
        return intents


def _merge_model_or_dict(current: Any, overlay: Any) -> Any:
    if hasattr(current, "model_copy"):
        if not isinstance(overlay, dict):
            raise RuntimeConfigInvalidError(
                "runtime variant model overlays must be objects",
                context={"overlay_type": type(overlay).__name__},
            )
        return current.model_copy(update=overlay)
    if isinstance(current, dict):
        if not isinstance(overlay, dict):
            raise RuntimeConfigInvalidError(
                "runtime variant dict overlays must be objects",
                context={"overlay_type": type(overlay).__name__},
            )
        return _deep_merge_dicts(current, overlay)
    return overlay


def _deep_merge_dicts(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge_dicts(merged[key], value)
        else:
            merged[key] = value
    return merged


def _candidate_selection_artifact_runtime_hashes(config: dict[str, Any]) -> list[str]:
    return _candidate_selection_artifact_runtime_hashes_with(config, selection_artifact_runtime_hash)


def _candidate_selection_artifact_runtime_hashes_v2(config: dict[str, Any]) -> list[str]:
    return _candidate_selection_artifact_runtime_hashes_with(config, selection_artifact_runtime_hash_v2)


def _candidate_selection_artifact_runtime_hashes_with(
    config: dict[str, Any],
    hash_builder: Any,
) -> list[str]:
    hashes: list[str] = []
    seen: set[str] = set()
    candidates = [config]
    normalized = normalize_selection_runtime_config(config)
    if normalized != config:
        candidates.append(normalized)
    profile = normalized.get("runtime_profile")
    if isinstance(profile, dict):
        stripped_profile = {
            key: value
            for key, value in profile.items()
            if key not in {"hmm", "risk_policy", "tradability", "industry_blacklist"}
        }
        stripped = dict(normalized)
        if stripped_profile:
            stripped["runtime_profile"] = stripped_profile
        else:
            stripped.pop("runtime_profile", None)
        candidates.append(stripped)
        candidates.append({})
    if "runtime_variant" in normalized:
        stripped_variant = dict(normalized)
        stripped_variant.pop("runtime_variant", None)
        candidates.append(stripped_variant)
        candidates.append({})
    for candidate in candidates:
        digest = hash_builder(candidate)
        if digest not in seen:
            hashes.append(digest)
            seen.add(digest)
    return hashes
