from __future__ import annotations

REQUIRED_PROMPT_FILES: list[str] = [
    "rdagent/app/CI/prompts.yaml",
    "rdagent/app/finetune/data_science/tpl/components/coder/data_science/pipeline/prompts.yaml",
    "rdagent/app/finetune/llm/prompts.yaml",
    "rdagent/app/finetune/llm/tpl/components/coder/data_science/pipeline/prompts.yaml",
    "rdagent/app/finetune/llm/tpl/scenarios/data_science/prompts.yaml",
    "rdagent/app/finetune/llm/tpl/scenarios/data_science/scen/prompts.yaml",
    "rdagent/app/finetune/share/prompts.yaml",
    "rdagent/app/qlib_rd_loop/prompts.yaml",
    "rdagent/app/utils/prompts.yaml",
    "rdagent/components/agent/context7/prompts.yaml",
    "rdagent/components/coder/CoSTEER/prompts.yaml",
    "rdagent/components/coder/data_science/ensemble/prompts.yaml",
    "rdagent/components/coder/data_science/feature/prompts.yaml",
    "rdagent/components/coder/data_science/model/prompts.yaml",
    "rdagent/components/coder/data_science/pipeline/prompts.yaml",
    "rdagent/components/coder/data_science/raw_data_loader/prompts.yaml",
    "rdagent/components/coder/data_science/share/prompts.yaml",
    "rdagent/components/coder/data_science/workflow/prompts.yaml",
    "rdagent/components/coder/factor_coder/prompts.yaml",
    "rdagent/components/coder/model_coder/prompts.yaml",
    "rdagent/components/proposal/prompts.yaml",
    "rdagent/scenarios/data_science/dev/prompts.yaml",
    "rdagent/scenarios/data_science/dev/runner/prompts.yaml",
    "rdagent/scenarios/data_science/proposal/exp_gen/prompts.yaml",
    "rdagent/scenarios/data_science/proposal/exp_gen/select/prompts.yaml",
    "rdagent/scenarios/data_science/scen/prompts.yaml",
    "rdagent/scenarios/general_model/prompts.yaml",
    "rdagent/scenarios/kaggle/experiment/prompts.yaml",
    "rdagent/scenarios/kaggle/knowledge_management/prompts.yaml",
    "rdagent/scenarios/kaggle/prompts.yaml",
    "rdagent/scenarios/qlib/experiment/prompts.yaml",
    "rdagent/scenarios/qlib/factor_experiment_loader/prompts.yaml",
    "rdagent/scenarios/qlib/prompts.yaml",
    "rdagent/utils/prompts.yaml",
]
